use std::collections::HashMap;
use std::io::Write;
use std::process::{Command, Stdio};

use crate::ast::{AssignTarget, BinaryOp, Expr, Program, Span, Stmt};
use crate::error::{CompileResult, Diagnostic, Phase};

pub fn emit_llvm_ir(program: &Program) -> CompileResult<String> {
    let mut generator = LlvmGenerator::default();
    generator.emit_program(program)
}

pub fn emit_assembly(program: &Program) -> CompileResult<String> {
    let ir = emit_llvm_ir(program)?;
    if command_available("clang") {
        return clang_assembly_from_ir(&ir);
    }
    if command_available("llc") {
        return llc_assembly_from_ir(&ir);
    }
    if command_available("cc") {
        let c_source = emit_c_source_for_assembly(program)?;
        return cc_assembly_from_c(&c_source);
    }

    Err(Diagnostic::new(
        Phase::Codegen,
        0,
        0,
        "no assembly backend found; install clang, llc, or cc",
    ))
}

#[derive(Default)]
struct LlvmGenerator {
    strings: Vec<(String, String)>,
    body: Vec<String>,
    variables: HashMap<String, IrValue>,
    next_temp: usize,
    next_string: usize,
}

#[derive(Debug, Clone)]
enum IrValue {
    Int(String),
    Float(String),
    String(String),
    Bool(bool),
    Null,
}

impl LlvmGenerator {
    fn emit_program(&mut self, program: &Program) -> CompileResult<String> {
        for stmt in &program.statements {
            self.emit_statement(stmt)?;
        }

        let mut output = String::new();
        output.push_str("; generated by phpc milestone 1\n");
        output.push_str("declare i32 @printf(ptr, ...)\n\n");
        output.push_str("@.fmt_int = private unnamed_addr constant [5 x i8] c\"%lld\\00\"\n");
        output.push_str("@.fmt_float = private unnamed_addr constant [3 x i8] c\"%g\\00\"\n");
        output.push_str("@.fmt_str = private unnamed_addr constant [3 x i8] c\"%s\\00\"\n");

        for (name, text) in &self.strings {
            output.push_str(&format!(
                "@{name} = private unnamed_addr constant [{} x i8] c\"{}\"\n",
                text.as_bytes().len() + 1,
                llvm_c_string(text)
            ));
        }

        output.push_str("\ndefine i32 @main() {\nentry:\n");
        for line in &self.body {
            output.push_str("  ");
            output.push_str(line);
            output.push('\n');
        }
        output.push_str("  ret i32 0\n}\n");
        Ok(output)
    }

    fn emit_statement(&mut self, stmt: &Stmt) -> CompileResult<()> {
        match stmt {
            Stmt::Echo { exprs, .. } => {
                for expr in exprs {
                    let value = self.emit_expr(expr)?;
                    self.emit_echo(value);
                }
                Ok(())
            }
            Stmt::Print { expr, .. } => {
                let value = self.emit_expr(expr)?;
                self.emit_echo(value);
                Ok(())
            }
            Stmt::Assign { target, expr, .. } => self.emit_assignment(target, expr),
            Stmt::Expr { expr, .. } => {
                self.emit_expr(expr)?;
                Ok(())
            }
            Stmt::Function(function) => Err(self.unsupported(
                function.span,
                "function declarations are not lowered to LLVM IR yet",
            )),
            Stmt::Class(class) => Err(self.unsupported(
                class.span,
                "class declarations are supported by phpc run metadata registration but not LLVM IR emission yet",
            )),
            Stmt::If { span, .. } => Err(self.unsupported(
                *span,
                "if/else is supported by phpc run but not LLVM IR emission yet",
            )),
            Stmt::While { span, .. } => Err(self.unsupported(
                *span,
                "while is supported by phpc run but not LLVM IR emission yet",
            )),
            Stmt::DoWhile { span, .. } => Err(self.unsupported(
                *span,
                "do-while loops are supported by phpc run but not LLVM IR emission yet",
            )),
            Stmt::For { span, .. } => Err(self.unsupported(
                *span,
                "for loops are supported by phpc run but not LLVM IR emission yet",
            )),
            Stmt::Switch { span, .. } => Err(self.unsupported(
                *span,
                "switch statements are supported by phpc run but not LLVM IR emission yet",
            )),
            Stmt::Foreach { span, .. } => Err(self.unsupported(
                *span,
                "foreach array iteration is supported by phpc run but not LLVM IR emission yet",
            )),
            Stmt::UnsetVariable { span, .. } => Err(self.unsupported(
                *span,
                "variable unset is supported by phpc run but not LLVM IR emission yet",
            )),
            Stmt::UnsetArrayIndex { span, .. } => Err(self.unsupported(
                *span,
                "array offset unset is supported by phpc run but not LLVM IR emission yet",
            )),
            Stmt::UnsetMany { span, .. } => Err(self.unsupported(
                *span,
                "multiple-operand unset is supported by phpc run but not LLVM IR emission yet",
            )),
            Stmt::Return { span, .. } => Err(self.unsupported(
                *span,
                "return is only valid inside functions, which are not lowered yet",
            )),
            Stmt::Break { span } => Err(self.unsupported(
                *span,
                "break is supported by phpc run for innermost loops but not LLVM IR emission yet",
            )),
            Stmt::Continue { span } => Err(self.unsupported(
                *span,
                "continue is supported by phpc run for innermost loops but not LLVM IR emission yet",
            )),
            Stmt::Global { span, .. } => Err(self.unsupported(
                *span,
                "global declarations are not supported by LLVM IR emission yet",
            )),
        }
    }

    fn emit_expr(&mut self, expr: &Expr) -> CompileResult<IrValue> {
        match expr {
            Expr::Null(_) => Ok(IrValue::Null),
            Expr::Bool(value, _) => Ok(IrValue::Bool(*value)),
            Expr::Int(value, _) => Ok(IrValue::Int(value.to_string())),
            Expr::Float(value, _) => Ok(IrValue::Float(format_float_literal(*value))),
            Expr::String(value, _) => Ok(IrValue::String(value.clone())),
            Expr::Array { span, .. } => Err(self.unsupported(
                *span,
                "arrays are supported by phpc run but not LLVM IR emission yet",
            )),
            Expr::Index { span, .. } => Err(self.unsupported(
                *span,
                "array indexing is supported by phpc run but not LLVM IR emission yet",
            )),
            Expr::Property { span, .. } => Err(self.unsupported(
                *span,
                "object property access is supported by phpc run but not LLVM IR emission yet",
            )),
            Expr::Variable(name, span) => self.variables.get(name).cloned().ok_or_else(|| {
                self.unsupported(
                    *span,
                    format!("variable '${name}' is not known in LLVM lowering"),
                )
            }),
            Expr::Call { span, .. } | Expr::DynamicCall { span, .. } => Err(self.unsupported(
                *span,
                "function calls are supported by phpc run but not LLVM IR emission yet",
            )),
            Expr::New { span, .. } => Err(self.unsupported(
                *span,
                "object instantiation is supported by phpc run but not LLVM IR emission yet",
            )),
            Expr::Unary { span, .. } => Err(self.unsupported(
                *span,
                "unary expressions are supported by phpc run but not LLVM IR emission yet",
            )),
            Expr::Binary {
                left,
                op,
                right,
                span,
            } => {
                let left = self.emit_expr(left)?;
                let right = self.emit_expr(right)?;
                self.emit_binary(left, *op, right, *span)
            }
        }
    }

    fn emit_assignment(&mut self, target: &AssignTarget, expr: &Expr) -> CompileResult<()> {
        match target {
            AssignTarget::Variable { name, .. } => {
                let value = self.emit_expr(expr)?;
                self.variables.insert(name.clone(), value);
                Ok(())
            }
            AssignTarget::ArrayIndex { span, .. } => Err(self.unsupported(
                *span,
                "array assignment is supported by phpc run but not LLVM IR emission yet",
            )),
            AssignTarget::Property { span, .. } => Err(self.unsupported(
                *span,
                "object property assignment is supported by phpc run but not LLVM IR emission yet",
            )),
        }
    }

    fn emit_binary(
        &mut self,
        left: IrValue,
        op: BinaryOp,
        right: IrValue,
        span: Span,
    ) -> CompileResult<IrValue> {
        match op {
            BinaryOp::Add | BinaryOp::Sub | BinaryOp::Mul => {
                self.emit_numeric_binary(left, op, right, span)
            }
            BinaryOp::Div => self.emit_div(left, right, span),
            BinaryOp::Concat => self.emit_concat(left, right, span),
            BinaryOp::Eq
            | BinaryOp::Ne
            | BinaryOp::Lt
            | BinaryOp::Le
            | BinaryOp::Gt
            | BinaryOp::Ge => Err(self.unsupported(
                span,
                "comparisons are supported by phpc run but not LLVM IR emission yet",
            )),
        }
    }

    fn emit_numeric_binary(
        &mut self,
        left: IrValue,
        op: BinaryOp,
        right: IrValue,
        span: Span,
    ) -> CompileResult<IrValue> {
        match (left, right) {
            (IrValue::Int(left), IrValue::Int(right)) => {
                let temp = self.temp();
                let instr = match op {
                    BinaryOp::Add => "add",
                    BinaryOp::Sub => "sub",
                    BinaryOp::Mul => "mul",
                    _ => unreachable!("caller restricts op"),
                };
                self.body
                    .push(format!("{temp} = {instr} i64 {left}, {right}"));
                Ok(IrValue::Int(temp))
            }
            (left, right) => {
                let left = self.into_float(left, span)?;
                let right = self.into_float(right, span)?;
                let temp = self.temp();
                let instr = match op {
                    BinaryOp::Add => "fadd",
                    BinaryOp::Sub => "fsub",
                    BinaryOp::Mul => "fmul",
                    _ => unreachable!("caller restricts op"),
                };
                self.body
                    .push(format!("{temp} = {instr} double {left}, {right}"));
                Ok(IrValue::Float(temp))
            }
        }
    }

    fn emit_div(&mut self, left: IrValue, right: IrValue, span: Span) -> CompileResult<IrValue> {
        let left = self.into_float(left, span)?;
        let right = self.into_float(right, span)?;
        let temp = self.temp();
        self.body
            .push(format!("{temp} = fdiv double {left}, {right}"));
        Ok(IrValue::Float(temp))
    }

    fn emit_concat(&mut self, left: IrValue, right: IrValue, span: Span) -> CompileResult<IrValue> {
        let left = self.const_echo_string(left).ok_or_else(|| {
            self.unsupported(
                span,
                "LLVM concat currently requires compile-time scalar operands",
            )
        })?;
        let right = self.const_echo_string(right).ok_or_else(|| {
            self.unsupported(
                span,
                "LLVM concat currently requires compile-time scalar operands",
            )
        })?;
        Ok(IrValue::String(format!("{left}{right}")))
    }

    fn emit_echo(&mut self, value: IrValue) {
        match value {
            IrValue::Null | IrValue::Bool(false) => {}
            IrValue::Bool(true) => {
                let global = self.add_string("1");
                self.body.push(format!(
                    "call i32 (ptr, ...) @printf(ptr @.fmt_str, ptr @{global})"
                ));
            }
            IrValue::Int(value) => {
                self.body.push(format!(
                    "call i32 (ptr, ...) @printf(ptr @.fmt_int, i64 {value})"
                ));
            }
            IrValue::Float(value) => {
                self.body.push(format!(
                    "call i32 (ptr, ...) @printf(ptr @.fmt_float, double {value})"
                ));
            }
            IrValue::String(value) => {
                let global = self.add_string(&value);
                self.body.push(format!(
                    "call i32 (ptr, ...) @printf(ptr @.fmt_str, ptr @{global})"
                ));
            }
        }
    }

    fn into_float(&mut self, value: IrValue, span: Span) -> CompileResult<String> {
        match value {
            IrValue::Float(value) => Ok(value),
            IrValue::Int(value) => {
                let temp = self.temp();
                self.body
                    .push(format!("{temp} = sitofp i64 {value} to double"));
                Ok(temp)
            }
            IrValue::Bool(value) => Ok(if value {
                "1.0".to_string()
            } else {
                "0.0".to_string()
            }),
            IrValue::Null => Ok("0.0".to_string()),
            IrValue::String(_) => Err(self.unsupported(
                span,
                "LLVM numeric lowering for strings is not implemented yet",
            )),
        }
    }

    fn const_echo_string(&self, value: IrValue) -> Option<String> {
        match value {
            IrValue::Null => Some(String::new()),
            IrValue::Bool(false) => Some(String::new()),
            IrValue::Bool(true) => Some("1".to_string()),
            IrValue::Int(value) if value.parse::<i64>().is_ok() => Some(value),
            IrValue::Float(value) if value.parse::<f64>().is_ok() => Some(value),
            IrValue::String(value) => Some(value),
            IrValue::Int(_) | IrValue::Float(_) => None,
        }
    }

    fn add_string(&mut self, value: &str) -> String {
        let name = format!(".str.{}", self.next_string);
        self.next_string += 1;
        self.strings.push((name.clone(), value.to_string()));
        name
    }

    fn temp(&mut self) -> String {
        let temp = format!("%t{}", self.next_temp);
        self.next_temp += 1;
        temp
    }

    fn unsupported(&self, span: Span, message: impl Into<String>) -> Diagnostic {
        Diagnostic::new(Phase::Codegen, span.line, span.column, message)
    }
}

fn clang_assembly_from_ir(ir: &str) -> CompileResult<String> {
    let mut child = Command::new("clang")
        .args(["-x", "ir", "-S", "-o", "-", "-"])
        .stdin(Stdio::piped())
        .stdout(Stdio::piped())
        .stderr(Stdio::piped())
        .spawn()
        .map_err(|error| {
            Diagnostic::new(
                Phase::Codegen,
                0,
                0,
                format!("failed to start clang for assembly emission: {error}"),
            )
        })?;

    {
        let stdin = child
            .stdin
            .as_mut()
            .ok_or_else(|| Diagnostic::new(Phase::Codegen, 0, 0, "failed to open clang stdin"))?;
        stdin.write_all(ir.as_bytes()).map_err(|error| {
            Diagnostic::new(
                Phase::Codegen,
                0,
                0,
                format!("failed to write LLVM IR to clang: {error}"),
            )
        })?;
    }

    let output = child.wait_with_output().map_err(|error| {
        Diagnostic::new(
            Phase::Codegen,
            0,
            0,
            format!("failed to wait for clang: {error}"),
        )
    })?;

    if !output.status.success() {
        let stderr = String::from_utf8_lossy(&output.stderr);
        return Err(Diagnostic::new(
            Phase::Codegen,
            0,
            0,
            format!("clang failed to emit assembly: {}", stderr.trim()),
        ));
    }

    Ok(String::from_utf8_lossy(&output.stdout).into_owned())
}

fn llc_assembly_from_ir(ir: &str) -> CompileResult<String> {
    let mut child = Command::new("llc")
        .args(["-o", "-", "-"])
        .stdin(Stdio::piped())
        .stdout(Stdio::piped())
        .stderr(Stdio::piped())
        .spawn()
        .map_err(|error| {
            Diagnostic::new(
                Phase::Codegen,
                0,
                0,
                format!("failed to start llc for assembly emission: {error}"),
            )
        })?;

    {
        let stdin = child
            .stdin
            .as_mut()
            .ok_or_else(|| Diagnostic::new(Phase::Codegen, 0, 0, "failed to open llc stdin"))?;
        stdin.write_all(ir.as_bytes()).map_err(|error| {
            Diagnostic::new(
                Phase::Codegen,
                0,
                0,
                format!("failed to write LLVM IR to llc: {error}"),
            )
        })?;
    }

    let output = child.wait_with_output().map_err(|error| {
        Diagnostic::new(
            Phase::Codegen,
            0,
            0,
            format!("failed to wait for llc: {error}"),
        )
    })?;

    if !output.status.success() {
        let stderr = String::from_utf8_lossy(&output.stderr);
        return Err(Diagnostic::new(
            Phase::Codegen,
            0,
            0,
            format!("llc failed to emit assembly: {}", stderr.trim()),
        ));
    }

    Ok(String::from_utf8_lossy(&output.stdout).into_owned())
}

fn cc_assembly_from_c(source: &str) -> CompileResult<String> {
    let mut child = Command::new("cc")
        .args(["-x", "c", "-S", "-o", "-", "-"])
        .stdin(Stdio::piped())
        .stdout(Stdio::piped())
        .stderr(Stdio::piped())
        .spawn()
        .map_err(|error| {
            Diagnostic::new(
                Phase::Codegen,
                0,
                0,
                format!("failed to start cc for assembly emission: {error}"),
            )
        })?;

    {
        let stdin = child
            .stdin
            .as_mut()
            .ok_or_else(|| Diagnostic::new(Phase::Codegen, 0, 0, "failed to open cc stdin"))?;
        stdin.write_all(source.as_bytes()).map_err(|error| {
            Diagnostic::new(
                Phase::Codegen,
                0,
                0,
                format!("failed to write C fallback source to cc: {error}"),
            )
        })?;
    }

    let output = child.wait_with_output().map_err(|error| {
        Diagnostic::new(
            Phase::Codegen,
            0,
            0,
            format!("failed to wait for cc: {error}"),
        )
    })?;

    if !output.status.success() {
        let stderr = String::from_utf8_lossy(&output.stderr);
        return Err(Diagnostic::new(
            Phase::Codegen,
            0,
            0,
            format!("cc failed to emit assembly: {}", stderr.trim()),
        ));
    }

    Ok(String::from_utf8_lossy(&output.stdout).into_owned())
}

fn command_available(command: &str) -> bool {
    Command::new(command)
        .arg("--version")
        .stdin(Stdio::null())
        .stdout(Stdio::null())
        .stderr(Stdio::null())
        .status()
        .map(|status| status.success())
        .unwrap_or(false)
}

fn emit_c_source_for_assembly(program: &Program) -> CompileResult<String> {
    let mut generator = CGenerator::default();
    generator.emit_program(program)
}

#[derive(Default)]
struct CGenerator {
    body: Vec<String>,
    variables: HashMap<String, CValue>,
    next_temp: usize,
}

#[derive(Debug, Clone)]
enum CValue {
    Int(String),
    Float(String),
    String(String),
    Bool(bool),
    Null,
}

impl CGenerator {
    fn emit_program(&mut self, program: &Program) -> CompileResult<String> {
        for stmt in &program.statements {
            self.emit_statement(stmt)?;
        }

        let mut output = String::new();
        output.push_str("/* generated by phpc milestone 1 C assembly fallback */\n");
        output.push_str("#include <stdio.h>\n\n");
        output.push_str("int main(void) {\n");
        for line in &self.body {
            output.push_str("  ");
            output.push_str(line);
            output.push('\n');
        }
        output.push_str("  return 0;\n");
        output.push_str("}\n");
        Ok(output)
    }

    fn emit_statement(&mut self, stmt: &Stmt) -> CompileResult<()> {
        match stmt {
            Stmt::Echo { exprs, .. } => {
                for expr in exprs {
                    let value = self.emit_expr(expr)?;
                    self.emit_echo(value);
                }
                Ok(())
            }
            Stmt::Print { expr, .. } => {
                let value = self.emit_expr(expr)?;
                self.emit_echo(value);
                Ok(())
            }
            Stmt::Assign { target, expr, .. } => self.emit_assignment(target, expr),
            Stmt::Expr { expr, .. } => {
                self.emit_expr(expr)?;
                Ok(())
            }
            Stmt::Function(function) => Err(self.unsupported(
                function.span,
                "function declarations are not lowered to assembly yet",
            )),
            Stmt::Class(class) => Err(self.unsupported(
                class.span,
                "class declarations are supported by phpc run metadata registration but not assembly emission yet",
            )),
            Stmt::If { span, .. } => Err(self.unsupported(
                *span,
                "if/else is supported by phpc run but not assembly emission yet",
            )),
            Stmt::While { span, .. } => Err(self.unsupported(
                *span,
                "while is supported by phpc run but not assembly emission yet",
            )),
            Stmt::DoWhile { span, .. } => Err(self.unsupported(
                *span,
                "do-while loops are supported by phpc run but not assembly emission yet",
            )),
            Stmt::For { span, .. } => Err(self.unsupported(
                *span,
                "for loops are supported by phpc run but not assembly emission yet",
            )),
            Stmt::Switch { span, .. } => Err(self.unsupported(
                *span,
                "switch statements are supported by phpc run but not assembly emission yet",
            )),
            Stmt::Foreach { span, .. } => Err(self.unsupported(
                *span,
                "foreach array iteration is supported by phpc run but not assembly emission yet",
            )),
            Stmt::UnsetVariable { span, .. } => Err(self.unsupported(
                *span,
                "variable unset is supported by phpc run but not assembly emission yet",
            )),
            Stmt::UnsetArrayIndex { span, .. } => Err(self.unsupported(
                *span,
                "array offset unset is supported by phpc run but not assembly emission yet",
            )),
            Stmt::UnsetMany { span, .. } => Err(self.unsupported(
                *span,
                "multiple-operand unset is supported by phpc run but not assembly emission yet",
            )),
            Stmt::Return { span, .. } => Err(self.unsupported(
                *span,
                "return is only valid inside functions, which are not lowered yet",
            )),
            Stmt::Break { span } => Err(self.unsupported(
                *span,
                "break is supported by phpc run for innermost loops but not assembly emission yet",
            )),
            Stmt::Continue { span } => Err(self.unsupported(
                *span,
                "continue is supported by phpc run for innermost loops but not assembly emission yet",
            )),
            Stmt::Global { span, .. } => Err(self.unsupported(
                *span,
                "global declarations are not supported by assembly emission yet",
            )),
        }
    }

    fn emit_expr(&mut self, expr: &Expr) -> CompileResult<CValue> {
        match expr {
            Expr::Null(_) => Ok(CValue::Null),
            Expr::Bool(value, _) => Ok(CValue::Bool(*value)),
            Expr::Int(value, _) => Ok(CValue::Int(value.to_string())),
            Expr::Float(value, _) => Ok(CValue::Float(format_float_literal(*value))),
            Expr::String(value, _) => Ok(CValue::String(value.clone())),
            Expr::Array { span, .. } => Err(self.unsupported(
                *span,
                "arrays are supported by phpc run but not assembly emission yet",
            )),
            Expr::Index { span, .. } => Err(self.unsupported(
                *span,
                "array indexing is supported by phpc run but not assembly emission yet",
            )),
            Expr::Property { span, .. } => Err(self.unsupported(
                *span,
                "object property access is supported by phpc run but not assembly emission yet",
            )),
            Expr::Variable(name, span) => self.variables.get(name).cloned().ok_or_else(|| {
                self.unsupported(
                    *span,
                    format!("variable '${name}' is not known in assembly lowering"),
                )
            }),
            Expr::Call { span, .. } | Expr::DynamicCall { span, .. } => Err(self.unsupported(
                *span,
                "function calls are supported by phpc run but not assembly emission yet",
            )),
            Expr::New { span, .. } => Err(self.unsupported(
                *span,
                "object instantiation is supported by phpc run but not assembly emission yet",
            )),
            Expr::Unary { span, .. } => Err(self.unsupported(
                *span,
                "unary expressions are supported by phpc run but not assembly emission yet",
            )),
            Expr::Binary {
                left,
                op,
                right,
                span,
            } => {
                let left = self.emit_expr(left)?;
                let right = self.emit_expr(right)?;
                self.emit_binary(left, *op, right, *span)
            }
        }
    }

    fn emit_assignment(&mut self, target: &AssignTarget, expr: &Expr) -> CompileResult<()> {
        match target {
            AssignTarget::Variable { name, .. } => {
                let value = self.emit_expr(expr)?;
                self.variables.insert(name.clone(), value);
                Ok(())
            }
            AssignTarget::ArrayIndex { span, .. } => Err(self.unsupported(
                *span,
                "array assignment is supported by phpc run but not assembly emission yet",
            )),
            AssignTarget::Property { span, .. } => Err(self.unsupported(
                *span,
                "object property assignment is supported by phpc run but not assembly emission yet",
            )),
        }
    }

    fn emit_binary(
        &mut self,
        left: CValue,
        op: BinaryOp,
        right: CValue,
        span: Span,
    ) -> CompileResult<CValue> {
        match op {
            BinaryOp::Add | BinaryOp::Sub | BinaryOp::Mul => {
                self.emit_numeric_binary(left, op, right, span)
            }
            BinaryOp::Div => self.emit_div(left, right, span),
            BinaryOp::Concat => self.emit_concat(left, right, span),
            BinaryOp::Eq
            | BinaryOp::Ne
            | BinaryOp::Lt
            | BinaryOp::Le
            | BinaryOp::Gt
            | BinaryOp::Ge => Err(self.unsupported(
                span,
                "comparisons are supported by phpc run but not assembly emission yet",
            )),
        }
    }

    fn emit_numeric_binary(
        &mut self,
        left: CValue,
        op: BinaryOp,
        right: CValue,
        span: Span,
    ) -> CompileResult<CValue> {
        let operator = match op {
            BinaryOp::Add => "+",
            BinaryOp::Sub => "-",
            BinaryOp::Mul => "*",
            _ => unreachable!("caller restricts op"),
        };

        match (left, right) {
            (CValue::Int(left), CValue::Int(right)) => {
                let temp = self.temp();
                self.body
                    .push(format!("long long {temp} = {left} {operator} {right};"));
                Ok(CValue::Int(temp))
            }
            (left, right) => {
                let left = self.into_float(left, span)?;
                let right = self.into_float(right, span)?;
                let temp = self.temp();
                self.body
                    .push(format!("double {temp} = {left} {operator} {right};"));
                Ok(CValue::Float(temp))
            }
        }
    }

    fn emit_div(&mut self, left: CValue, right: CValue, span: Span) -> CompileResult<CValue> {
        let left = self.into_float(left, span)?;
        let right = self.into_float(right, span)?;
        let temp = self.temp();
        self.body.push(format!("double {temp} = {left} / {right};"));
        Ok(CValue::Float(temp))
    }

    fn emit_concat(&mut self, left: CValue, right: CValue, span: Span) -> CompileResult<CValue> {
        let left = self.const_echo_string(left).ok_or_else(|| {
            self.unsupported(
                span,
                "assembly concat currently requires compile-time scalar operands",
            )
        })?;
        let right = self.const_echo_string(right).ok_or_else(|| {
            self.unsupported(
                span,
                "assembly concat currently requires compile-time scalar operands",
            )
        })?;
        Ok(CValue::String(format!("{left}{right}")))
    }

    fn emit_echo(&mut self, value: CValue) {
        match value {
            CValue::Null | CValue::Bool(false) => {}
            CValue::Bool(true) => self.body.push("printf(\"%s\", \"1\");".to_string()),
            CValue::Int(value) => self.body.push(format!("printf(\"%lld\", {value});")),
            CValue::Float(value) => self.body.push(format!("printf(\"%g\", {value});")),
            CValue::String(value) => self
                .body
                .push(format!("printf(\"%s\", \"{}\");", c_string(&value))),
        }
    }

    fn into_float(&self, value: CValue, span: Span) -> CompileResult<String> {
        match value {
            CValue::Float(value) => Ok(value),
            CValue::Int(value) => Ok(format!("(double)({value})")),
            CValue::Bool(value) => Ok(if value {
                "1.0".to_string()
            } else {
                "0.0".to_string()
            }),
            CValue::Null => Ok("0.0".to_string()),
            CValue::String(_) => Err(self.unsupported(
                span,
                "assembly numeric lowering for strings is not implemented yet",
            )),
        }
    }

    fn const_echo_string(&self, value: CValue) -> Option<String> {
        match value {
            CValue::Null => Some(String::new()),
            CValue::Bool(false) => Some(String::new()),
            CValue::Bool(true) => Some("1".to_string()),
            CValue::Int(value) if value.parse::<i64>().is_ok() => Some(value),
            CValue::Float(value) if value.parse::<f64>().is_ok() => Some(value),
            CValue::String(value) => Some(value),
            CValue::Int(_) | CValue::Float(_) => None,
        }
    }

    fn temp(&mut self) -> String {
        let temp = format!("t{}", self.next_temp);
        self.next_temp += 1;
        temp
    }

    fn unsupported(&self, span: Span, message: impl Into<String>) -> Diagnostic {
        Diagnostic::new(Phase::Codegen, span.line, span.column, message)
    }
}

fn llvm_c_string(value: &str) -> String {
    let mut escaped = String::new();
    for byte in value.as_bytes() {
        match *byte {
            b'\\' => escaped.push_str("\\5C"),
            b'"' => escaped.push_str("\\22"),
            b'\n' => escaped.push_str("\\0A"),
            b'\r' => escaped.push_str("\\0D"),
            b'\t' => escaped.push_str("\\09"),
            0x20..=0x7e => escaped.push(*byte as char),
            other => escaped.push_str(&format!("\\{other:02X}")),
        }
    }
    escaped.push_str("\\00");
    escaped
}

fn c_string(value: &str) -> String {
    let mut escaped = String::new();
    for ch in value.chars() {
        match ch {
            '\\' => escaped.push_str("\\\\"),
            '"' => escaped.push_str("\\\""),
            '\n' => escaped.push_str("\\n"),
            '\r' => escaped.push_str("\\r"),
            '\t' => escaped.push_str("\\t"),
            ch if ch.is_ascii_graphic() || ch == ' ' => escaped.push(ch),
            ch => escaped.push_str(&format!("\\x{:02X}", ch as u32)),
        }
    }
    escaped
}

fn format_float_literal(value: f64) -> String {
    if value.fract() == 0.0 {
        format!("{value:.1}")
    } else {
        value.to_string()
    }
}
