// Generated from the host PHP get_html_translation_table() for HTML4 tables
// and single-byte charset maps consumed by bounded interpreter HTML entity builtins.

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct HtmlEntityTranslation {
    pub entity: &'static str,
    pub codepoints: &'static [u32],
}

pub static HTML4_ENCODE_ENTITIES: &[HtmlEntityTranslation] = &[
    HtmlEntityTranslation {
        entity: "&quot;",
        codepoints: &[0x22],
    },
    HtmlEntityTranslation {
        entity: "&amp;",
        codepoints: &[0x26],
    },
    HtmlEntityTranslation {
        entity: "&#039;",
        codepoints: &[0x27],
    },
    HtmlEntityTranslation {
        entity: "&lt;",
        codepoints: &[0x3C],
    },
    HtmlEntityTranslation {
        entity: "&gt;",
        codepoints: &[0x3E],
    },
    HtmlEntityTranslation {
        entity: "&nbsp;",
        codepoints: &[0xA0],
    },
    HtmlEntityTranslation {
        entity: "&iexcl;",
        codepoints: &[0xA1],
    },
    HtmlEntityTranslation {
        entity: "&cent;",
        codepoints: &[0xA2],
    },
    HtmlEntityTranslation {
        entity: "&pound;",
        codepoints: &[0xA3],
    },
    HtmlEntityTranslation {
        entity: "&curren;",
        codepoints: &[0xA4],
    },
    HtmlEntityTranslation {
        entity: "&yen;",
        codepoints: &[0xA5],
    },
    HtmlEntityTranslation {
        entity: "&brvbar;",
        codepoints: &[0xA6],
    },
    HtmlEntityTranslation {
        entity: "&sect;",
        codepoints: &[0xA7],
    },
    HtmlEntityTranslation {
        entity: "&uml;",
        codepoints: &[0xA8],
    },
    HtmlEntityTranslation {
        entity: "&copy;",
        codepoints: &[0xA9],
    },
    HtmlEntityTranslation {
        entity: "&ordf;",
        codepoints: &[0xAA],
    },
    HtmlEntityTranslation {
        entity: "&laquo;",
        codepoints: &[0xAB],
    },
    HtmlEntityTranslation {
        entity: "&not;",
        codepoints: &[0xAC],
    },
    HtmlEntityTranslation {
        entity: "&shy;",
        codepoints: &[0xAD],
    },
    HtmlEntityTranslation {
        entity: "&reg;",
        codepoints: &[0xAE],
    },
    HtmlEntityTranslation {
        entity: "&macr;",
        codepoints: &[0xAF],
    },
    HtmlEntityTranslation {
        entity: "&deg;",
        codepoints: &[0xB0],
    },
    HtmlEntityTranslation {
        entity: "&plusmn;",
        codepoints: &[0xB1],
    },
    HtmlEntityTranslation {
        entity: "&sup2;",
        codepoints: &[0xB2],
    },
    HtmlEntityTranslation {
        entity: "&sup3;",
        codepoints: &[0xB3],
    },
    HtmlEntityTranslation {
        entity: "&acute;",
        codepoints: &[0xB4],
    },
    HtmlEntityTranslation {
        entity: "&micro;",
        codepoints: &[0xB5],
    },
    HtmlEntityTranslation {
        entity: "&para;",
        codepoints: &[0xB6],
    },
    HtmlEntityTranslation {
        entity: "&middot;",
        codepoints: &[0xB7],
    },
    HtmlEntityTranslation {
        entity: "&cedil;",
        codepoints: &[0xB8],
    },
    HtmlEntityTranslation {
        entity: "&sup1;",
        codepoints: &[0xB9],
    },
    HtmlEntityTranslation {
        entity: "&ordm;",
        codepoints: &[0xBA],
    },
    HtmlEntityTranslation {
        entity: "&raquo;",
        codepoints: &[0xBB],
    },
    HtmlEntityTranslation {
        entity: "&frac14;",
        codepoints: &[0xBC],
    },
    HtmlEntityTranslation {
        entity: "&frac12;",
        codepoints: &[0xBD],
    },
    HtmlEntityTranslation {
        entity: "&frac34;",
        codepoints: &[0xBE],
    },
    HtmlEntityTranslation {
        entity: "&iquest;",
        codepoints: &[0xBF],
    },
    HtmlEntityTranslation {
        entity: "&Agrave;",
        codepoints: &[0xC0],
    },
    HtmlEntityTranslation {
        entity: "&Aacute;",
        codepoints: &[0xC1],
    },
    HtmlEntityTranslation {
        entity: "&Acirc;",
        codepoints: &[0xC2],
    },
    HtmlEntityTranslation {
        entity: "&Atilde;",
        codepoints: &[0xC3],
    },
    HtmlEntityTranslation {
        entity: "&Auml;",
        codepoints: &[0xC4],
    },
    HtmlEntityTranslation {
        entity: "&Aring;",
        codepoints: &[0xC5],
    },
    HtmlEntityTranslation {
        entity: "&AElig;",
        codepoints: &[0xC6],
    },
    HtmlEntityTranslation {
        entity: "&Ccedil;",
        codepoints: &[0xC7],
    },
    HtmlEntityTranslation {
        entity: "&Egrave;",
        codepoints: &[0xC8],
    },
    HtmlEntityTranslation {
        entity: "&Eacute;",
        codepoints: &[0xC9],
    },
    HtmlEntityTranslation {
        entity: "&Ecirc;",
        codepoints: &[0xCA],
    },
    HtmlEntityTranslation {
        entity: "&Euml;",
        codepoints: &[0xCB],
    },
    HtmlEntityTranslation {
        entity: "&Igrave;",
        codepoints: &[0xCC],
    },
    HtmlEntityTranslation {
        entity: "&Iacute;",
        codepoints: &[0xCD],
    },
    HtmlEntityTranslation {
        entity: "&Icirc;",
        codepoints: &[0xCE],
    },
    HtmlEntityTranslation {
        entity: "&Iuml;",
        codepoints: &[0xCF],
    },
    HtmlEntityTranslation {
        entity: "&ETH;",
        codepoints: &[0xD0],
    },
    HtmlEntityTranslation {
        entity: "&Ntilde;",
        codepoints: &[0xD1],
    },
    HtmlEntityTranslation {
        entity: "&Ograve;",
        codepoints: &[0xD2],
    },
    HtmlEntityTranslation {
        entity: "&Oacute;",
        codepoints: &[0xD3],
    },
    HtmlEntityTranslation {
        entity: "&Ocirc;",
        codepoints: &[0xD4],
    },
    HtmlEntityTranslation {
        entity: "&Otilde;",
        codepoints: &[0xD5],
    },
    HtmlEntityTranslation {
        entity: "&Ouml;",
        codepoints: &[0xD6],
    },
    HtmlEntityTranslation {
        entity: "&times;",
        codepoints: &[0xD7],
    },
    HtmlEntityTranslation {
        entity: "&Oslash;",
        codepoints: &[0xD8],
    },
    HtmlEntityTranslation {
        entity: "&Ugrave;",
        codepoints: &[0xD9],
    },
    HtmlEntityTranslation {
        entity: "&Uacute;",
        codepoints: &[0xDA],
    },
    HtmlEntityTranslation {
        entity: "&Ucirc;",
        codepoints: &[0xDB],
    },
    HtmlEntityTranslation {
        entity: "&Uuml;",
        codepoints: &[0xDC],
    },
    HtmlEntityTranslation {
        entity: "&Yacute;",
        codepoints: &[0xDD],
    },
    HtmlEntityTranslation {
        entity: "&THORN;",
        codepoints: &[0xDE],
    },
    HtmlEntityTranslation {
        entity: "&szlig;",
        codepoints: &[0xDF],
    },
    HtmlEntityTranslation {
        entity: "&agrave;",
        codepoints: &[0xE0],
    },
    HtmlEntityTranslation {
        entity: "&aacute;",
        codepoints: &[0xE1],
    },
    HtmlEntityTranslation {
        entity: "&acirc;",
        codepoints: &[0xE2],
    },
    HtmlEntityTranslation {
        entity: "&atilde;",
        codepoints: &[0xE3],
    },
    HtmlEntityTranslation {
        entity: "&auml;",
        codepoints: &[0xE4],
    },
    HtmlEntityTranslation {
        entity: "&aring;",
        codepoints: &[0xE5],
    },
    HtmlEntityTranslation {
        entity: "&aelig;",
        codepoints: &[0xE6],
    },
    HtmlEntityTranslation {
        entity: "&ccedil;",
        codepoints: &[0xE7],
    },
    HtmlEntityTranslation {
        entity: "&egrave;",
        codepoints: &[0xE8],
    },
    HtmlEntityTranslation {
        entity: "&eacute;",
        codepoints: &[0xE9],
    },
    HtmlEntityTranslation {
        entity: "&ecirc;",
        codepoints: &[0xEA],
    },
    HtmlEntityTranslation {
        entity: "&euml;",
        codepoints: &[0xEB],
    },
    HtmlEntityTranslation {
        entity: "&igrave;",
        codepoints: &[0xEC],
    },
    HtmlEntityTranslation {
        entity: "&iacute;",
        codepoints: &[0xED],
    },
    HtmlEntityTranslation {
        entity: "&icirc;",
        codepoints: &[0xEE],
    },
    HtmlEntityTranslation {
        entity: "&iuml;",
        codepoints: &[0xEF],
    },
    HtmlEntityTranslation {
        entity: "&eth;",
        codepoints: &[0xF0],
    },
    HtmlEntityTranslation {
        entity: "&ntilde;",
        codepoints: &[0xF1],
    },
    HtmlEntityTranslation {
        entity: "&ograve;",
        codepoints: &[0xF2],
    },
    HtmlEntityTranslation {
        entity: "&oacute;",
        codepoints: &[0xF3],
    },
    HtmlEntityTranslation {
        entity: "&ocirc;",
        codepoints: &[0xF4],
    },
    HtmlEntityTranslation {
        entity: "&otilde;",
        codepoints: &[0xF5],
    },
    HtmlEntityTranslation {
        entity: "&ouml;",
        codepoints: &[0xF6],
    },
    HtmlEntityTranslation {
        entity: "&divide;",
        codepoints: &[0xF7],
    },
    HtmlEntityTranslation {
        entity: "&oslash;",
        codepoints: &[0xF8],
    },
    HtmlEntityTranslation {
        entity: "&ugrave;",
        codepoints: &[0xF9],
    },
    HtmlEntityTranslation {
        entity: "&uacute;",
        codepoints: &[0xFA],
    },
    HtmlEntityTranslation {
        entity: "&ucirc;",
        codepoints: &[0xFB],
    },
    HtmlEntityTranslation {
        entity: "&uuml;",
        codepoints: &[0xFC],
    },
    HtmlEntityTranslation {
        entity: "&yacute;",
        codepoints: &[0xFD],
    },
    HtmlEntityTranslation {
        entity: "&thorn;",
        codepoints: &[0xFE],
    },
    HtmlEntityTranslation {
        entity: "&yuml;",
        codepoints: &[0xFF],
    },
    HtmlEntityTranslation {
        entity: "&OElig;",
        codepoints: &[0x152],
    },
    HtmlEntityTranslation {
        entity: "&oelig;",
        codepoints: &[0x153],
    },
    HtmlEntityTranslation {
        entity: "&Scaron;",
        codepoints: &[0x160],
    },
    HtmlEntityTranslation {
        entity: "&scaron;",
        codepoints: &[0x161],
    },
    HtmlEntityTranslation {
        entity: "&Yuml;",
        codepoints: &[0x178],
    },
    HtmlEntityTranslation {
        entity: "&fnof;",
        codepoints: &[0x192],
    },
    HtmlEntityTranslation {
        entity: "&circ;",
        codepoints: &[0x2C6],
    },
    HtmlEntityTranslation {
        entity: "&tilde;",
        codepoints: &[0x2DC],
    },
    HtmlEntityTranslation {
        entity: "&Alpha;",
        codepoints: &[0x391],
    },
    HtmlEntityTranslation {
        entity: "&Beta;",
        codepoints: &[0x392],
    },
    HtmlEntityTranslation {
        entity: "&Gamma;",
        codepoints: &[0x393],
    },
    HtmlEntityTranslation {
        entity: "&Delta;",
        codepoints: &[0x394],
    },
    HtmlEntityTranslation {
        entity: "&Epsilon;",
        codepoints: &[0x395],
    },
    HtmlEntityTranslation {
        entity: "&Zeta;",
        codepoints: &[0x396],
    },
    HtmlEntityTranslation {
        entity: "&Eta;",
        codepoints: &[0x397],
    },
    HtmlEntityTranslation {
        entity: "&Theta;",
        codepoints: &[0x398],
    },
    HtmlEntityTranslation {
        entity: "&Iota;",
        codepoints: &[0x399],
    },
    HtmlEntityTranslation {
        entity: "&Kappa;",
        codepoints: &[0x39A],
    },
    HtmlEntityTranslation {
        entity: "&Lambda;",
        codepoints: &[0x39B],
    },
    HtmlEntityTranslation {
        entity: "&Mu;",
        codepoints: &[0x39C],
    },
    HtmlEntityTranslation {
        entity: "&Nu;",
        codepoints: &[0x39D],
    },
    HtmlEntityTranslation {
        entity: "&Xi;",
        codepoints: &[0x39E],
    },
    HtmlEntityTranslation {
        entity: "&Omicron;",
        codepoints: &[0x39F],
    },
    HtmlEntityTranslation {
        entity: "&Pi;",
        codepoints: &[0x3A0],
    },
    HtmlEntityTranslation {
        entity: "&Rho;",
        codepoints: &[0x3A1],
    },
    HtmlEntityTranslation {
        entity: "&Sigma;",
        codepoints: &[0x3A3],
    },
    HtmlEntityTranslation {
        entity: "&Tau;",
        codepoints: &[0x3A4],
    },
    HtmlEntityTranslation {
        entity: "&Upsilon;",
        codepoints: &[0x3A5],
    },
    HtmlEntityTranslation {
        entity: "&Phi;",
        codepoints: &[0x3A6],
    },
    HtmlEntityTranslation {
        entity: "&Chi;",
        codepoints: &[0x3A7],
    },
    HtmlEntityTranslation {
        entity: "&Psi;",
        codepoints: &[0x3A8],
    },
    HtmlEntityTranslation {
        entity: "&Omega;",
        codepoints: &[0x3A9],
    },
    HtmlEntityTranslation {
        entity: "&alpha;",
        codepoints: &[0x3B1],
    },
    HtmlEntityTranslation {
        entity: "&beta;",
        codepoints: &[0x3B2],
    },
    HtmlEntityTranslation {
        entity: "&gamma;",
        codepoints: &[0x3B3],
    },
    HtmlEntityTranslation {
        entity: "&delta;",
        codepoints: &[0x3B4],
    },
    HtmlEntityTranslation {
        entity: "&epsilon;",
        codepoints: &[0x3B5],
    },
    HtmlEntityTranslation {
        entity: "&zeta;",
        codepoints: &[0x3B6],
    },
    HtmlEntityTranslation {
        entity: "&eta;",
        codepoints: &[0x3B7],
    },
    HtmlEntityTranslation {
        entity: "&theta;",
        codepoints: &[0x3B8],
    },
    HtmlEntityTranslation {
        entity: "&iota;",
        codepoints: &[0x3B9],
    },
    HtmlEntityTranslation {
        entity: "&kappa;",
        codepoints: &[0x3BA],
    },
    HtmlEntityTranslation {
        entity: "&lambda;",
        codepoints: &[0x3BB],
    },
    HtmlEntityTranslation {
        entity: "&mu;",
        codepoints: &[0x3BC],
    },
    HtmlEntityTranslation {
        entity: "&nu;",
        codepoints: &[0x3BD],
    },
    HtmlEntityTranslation {
        entity: "&xi;",
        codepoints: &[0x3BE],
    },
    HtmlEntityTranslation {
        entity: "&omicron;",
        codepoints: &[0x3BF],
    },
    HtmlEntityTranslation {
        entity: "&pi;",
        codepoints: &[0x3C0],
    },
    HtmlEntityTranslation {
        entity: "&rho;",
        codepoints: &[0x3C1],
    },
    HtmlEntityTranslation {
        entity: "&sigmaf;",
        codepoints: &[0x3C2],
    },
    HtmlEntityTranslation {
        entity: "&sigma;",
        codepoints: &[0x3C3],
    },
    HtmlEntityTranslation {
        entity: "&tau;",
        codepoints: &[0x3C4],
    },
    HtmlEntityTranslation {
        entity: "&upsilon;",
        codepoints: &[0x3C5],
    },
    HtmlEntityTranslation {
        entity: "&phi;",
        codepoints: &[0x3C6],
    },
    HtmlEntityTranslation {
        entity: "&chi;",
        codepoints: &[0x3C7],
    },
    HtmlEntityTranslation {
        entity: "&psi;",
        codepoints: &[0x3C8],
    },
    HtmlEntityTranslation {
        entity: "&omega;",
        codepoints: &[0x3C9],
    },
    HtmlEntityTranslation {
        entity: "&thetasym;",
        codepoints: &[0x3D1],
    },
    HtmlEntityTranslation {
        entity: "&upsih;",
        codepoints: &[0x3D2],
    },
    HtmlEntityTranslation {
        entity: "&piv;",
        codepoints: &[0x3D6],
    },
    HtmlEntityTranslation {
        entity: "&ensp;",
        codepoints: &[0x2002],
    },
    HtmlEntityTranslation {
        entity: "&emsp;",
        codepoints: &[0x2003],
    },
    HtmlEntityTranslation {
        entity: "&thinsp;",
        codepoints: &[0x2009],
    },
    HtmlEntityTranslation {
        entity: "&zwnj;",
        codepoints: &[0x200C],
    },
    HtmlEntityTranslation {
        entity: "&zwj;",
        codepoints: &[0x200D],
    },
    HtmlEntityTranslation {
        entity: "&lrm;",
        codepoints: &[0x200E],
    },
    HtmlEntityTranslation {
        entity: "&rlm;",
        codepoints: &[0x200F],
    },
    HtmlEntityTranslation {
        entity: "&ndash;",
        codepoints: &[0x2013],
    },
    HtmlEntityTranslation {
        entity: "&mdash;",
        codepoints: &[0x2014],
    },
    HtmlEntityTranslation {
        entity: "&lsquo;",
        codepoints: &[0x2018],
    },
    HtmlEntityTranslation {
        entity: "&rsquo;",
        codepoints: &[0x2019],
    },
    HtmlEntityTranslation {
        entity: "&sbquo;",
        codepoints: &[0x201A],
    },
    HtmlEntityTranslation {
        entity: "&ldquo;",
        codepoints: &[0x201C],
    },
    HtmlEntityTranslation {
        entity: "&rdquo;",
        codepoints: &[0x201D],
    },
    HtmlEntityTranslation {
        entity: "&bdquo;",
        codepoints: &[0x201E],
    },
    HtmlEntityTranslation {
        entity: "&dagger;",
        codepoints: &[0x2020],
    },
    HtmlEntityTranslation {
        entity: "&Dagger;",
        codepoints: &[0x2021],
    },
    HtmlEntityTranslation {
        entity: "&bull;",
        codepoints: &[0x2022],
    },
    HtmlEntityTranslation {
        entity: "&hellip;",
        codepoints: &[0x2026],
    },
    HtmlEntityTranslation {
        entity: "&permil;",
        codepoints: &[0x2030],
    },
    HtmlEntityTranslation {
        entity: "&prime;",
        codepoints: &[0x2032],
    },
    HtmlEntityTranslation {
        entity: "&Prime;",
        codepoints: &[0x2033],
    },
    HtmlEntityTranslation {
        entity: "&lsaquo;",
        codepoints: &[0x2039],
    },
    HtmlEntityTranslation {
        entity: "&rsaquo;",
        codepoints: &[0x203A],
    },
    HtmlEntityTranslation {
        entity: "&oline;",
        codepoints: &[0x203E],
    },
    HtmlEntityTranslation {
        entity: "&frasl;",
        codepoints: &[0x2044],
    },
    HtmlEntityTranslation {
        entity: "&euro;",
        codepoints: &[0x20AC],
    },
    HtmlEntityTranslation {
        entity: "&image;",
        codepoints: &[0x2111],
    },
    HtmlEntityTranslation {
        entity: "&weierp;",
        codepoints: &[0x2118],
    },
    HtmlEntityTranslation {
        entity: "&real;",
        codepoints: &[0x211C],
    },
    HtmlEntityTranslation {
        entity: "&trade;",
        codepoints: &[0x2122],
    },
    HtmlEntityTranslation {
        entity: "&alefsym;",
        codepoints: &[0x2135],
    },
    HtmlEntityTranslation {
        entity: "&larr;",
        codepoints: &[0x2190],
    },
    HtmlEntityTranslation {
        entity: "&uarr;",
        codepoints: &[0x2191],
    },
    HtmlEntityTranslation {
        entity: "&rarr;",
        codepoints: &[0x2192],
    },
    HtmlEntityTranslation {
        entity: "&darr;",
        codepoints: &[0x2193],
    },
    HtmlEntityTranslation {
        entity: "&harr;",
        codepoints: &[0x2194],
    },
    HtmlEntityTranslation {
        entity: "&crarr;",
        codepoints: &[0x21B5],
    },
    HtmlEntityTranslation {
        entity: "&lArr;",
        codepoints: &[0x21D0],
    },
    HtmlEntityTranslation {
        entity: "&uArr;",
        codepoints: &[0x21D1],
    },
    HtmlEntityTranslation {
        entity: "&rArr;",
        codepoints: &[0x21D2],
    },
    HtmlEntityTranslation {
        entity: "&dArr;",
        codepoints: &[0x21D3],
    },
    HtmlEntityTranslation {
        entity: "&hArr;",
        codepoints: &[0x21D4],
    },
    HtmlEntityTranslation {
        entity: "&forall;",
        codepoints: &[0x2200],
    },
    HtmlEntityTranslation {
        entity: "&part;",
        codepoints: &[0x2202],
    },
    HtmlEntityTranslation {
        entity: "&exist;",
        codepoints: &[0x2203],
    },
    HtmlEntityTranslation {
        entity: "&empty;",
        codepoints: &[0x2205],
    },
    HtmlEntityTranslation {
        entity: "&nabla;",
        codepoints: &[0x2207],
    },
    HtmlEntityTranslation {
        entity: "&isin;",
        codepoints: &[0x2208],
    },
    HtmlEntityTranslation {
        entity: "&notin;",
        codepoints: &[0x2209],
    },
    HtmlEntityTranslation {
        entity: "&ni;",
        codepoints: &[0x220B],
    },
    HtmlEntityTranslation {
        entity: "&prod;",
        codepoints: &[0x220F],
    },
    HtmlEntityTranslation {
        entity: "&sum;",
        codepoints: &[0x2211],
    },
    HtmlEntityTranslation {
        entity: "&minus;",
        codepoints: &[0x2212],
    },
    HtmlEntityTranslation {
        entity: "&lowast;",
        codepoints: &[0x2217],
    },
    HtmlEntityTranslation {
        entity: "&radic;",
        codepoints: &[0x221A],
    },
    HtmlEntityTranslation {
        entity: "&prop;",
        codepoints: &[0x221D],
    },
    HtmlEntityTranslation {
        entity: "&infin;",
        codepoints: &[0x221E],
    },
    HtmlEntityTranslation {
        entity: "&ang;",
        codepoints: &[0x2220],
    },
    HtmlEntityTranslation {
        entity: "&and;",
        codepoints: &[0x2227],
    },
    HtmlEntityTranslation {
        entity: "&or;",
        codepoints: &[0x2228],
    },
    HtmlEntityTranslation {
        entity: "&cap;",
        codepoints: &[0x2229],
    },
    HtmlEntityTranslation {
        entity: "&cup;",
        codepoints: &[0x222A],
    },
    HtmlEntityTranslation {
        entity: "&int;",
        codepoints: &[0x222B],
    },
    HtmlEntityTranslation {
        entity: "&there4;",
        codepoints: &[0x2234],
    },
    HtmlEntityTranslation {
        entity: "&sim;",
        codepoints: &[0x223C],
    },
    HtmlEntityTranslation {
        entity: "&cong;",
        codepoints: &[0x2245],
    },
    HtmlEntityTranslation {
        entity: "&asymp;",
        codepoints: &[0x2248],
    },
    HtmlEntityTranslation {
        entity: "&ne;",
        codepoints: &[0x2260],
    },
    HtmlEntityTranslation {
        entity: "&equiv;",
        codepoints: &[0x2261],
    },
    HtmlEntityTranslation {
        entity: "&le;",
        codepoints: &[0x2264],
    },
    HtmlEntityTranslation {
        entity: "&ge;",
        codepoints: &[0x2265],
    },
    HtmlEntityTranslation {
        entity: "&sub;",
        codepoints: &[0x2282],
    },
    HtmlEntityTranslation {
        entity: "&sup;",
        codepoints: &[0x2283],
    },
    HtmlEntityTranslation {
        entity: "&nsub;",
        codepoints: &[0x2284],
    },
    HtmlEntityTranslation {
        entity: "&sube;",
        codepoints: &[0x2286],
    },
    HtmlEntityTranslation {
        entity: "&supe;",
        codepoints: &[0x2287],
    },
    HtmlEntityTranslation {
        entity: "&oplus;",
        codepoints: &[0x2295],
    },
    HtmlEntityTranslation {
        entity: "&otimes;",
        codepoints: &[0x2297],
    },
    HtmlEntityTranslation {
        entity: "&perp;",
        codepoints: &[0x22A5],
    },
    HtmlEntityTranslation {
        entity: "&sdot;",
        codepoints: &[0x22C5],
    },
    HtmlEntityTranslation {
        entity: "&lceil;",
        codepoints: &[0x2308],
    },
    HtmlEntityTranslation {
        entity: "&rceil;",
        codepoints: &[0x2309],
    },
    HtmlEntityTranslation {
        entity: "&lfloor;",
        codepoints: &[0x230A],
    },
    HtmlEntityTranslation {
        entity: "&rfloor;",
        codepoints: &[0x230B],
    },
    HtmlEntityTranslation {
        entity: "&lang;",
        codepoints: &[0x2329],
    },
    HtmlEntityTranslation {
        entity: "&rang;",
        codepoints: &[0x232A],
    },
    HtmlEntityTranslation {
        entity: "&loz;",
        codepoints: &[0x25CA],
    },
    HtmlEntityTranslation {
        entity: "&spades;",
        codepoints: &[0x2660],
    },
    HtmlEntityTranslation {
        entity: "&clubs;",
        codepoints: &[0x2663],
    },
    HtmlEntityTranslation {
        entity: "&hearts;",
        codepoints: &[0x2665],
    },
    HtmlEntityTranslation {
        entity: "&diams;",
        codepoints: &[0x2666],
    },
];
pub static HTML4_DECODE_ENTITIES: &[HtmlEntityTranslation] = &[
    HtmlEntityTranslation {
        entity: "&thetasym;",
        codepoints: &[0x3D1],
    },
    HtmlEntityTranslation {
        entity: "&Epsilon;",
        codepoints: &[0x395],
    },
    HtmlEntityTranslation {
        entity: "&Omicron;",
        codepoints: &[0x39F],
    },
    HtmlEntityTranslation {
        entity: "&Upsilon;",
        codepoints: &[0x3A5],
    },
    HtmlEntityTranslation {
        entity: "&alefsym;",
        codepoints: &[0x2135],
    },
    HtmlEntityTranslation {
        entity: "&epsilon;",
        codepoints: &[0x3B5],
    },
    HtmlEntityTranslation {
        entity: "&omicron;",
        codepoints: &[0x3BF],
    },
    HtmlEntityTranslation {
        entity: "&upsilon;",
        codepoints: &[0x3C5],
    },
    HtmlEntityTranslation {
        entity: "&Aacute;",
        codepoints: &[0xC1],
    },
    HtmlEntityTranslation {
        entity: "&Agrave;",
        codepoints: &[0xC0],
    },
    HtmlEntityTranslation {
        entity: "&Atilde;",
        codepoints: &[0xC3],
    },
    HtmlEntityTranslation {
        entity: "&Ccedil;",
        codepoints: &[0xC7],
    },
    HtmlEntityTranslation {
        entity: "&Dagger;",
        codepoints: &[0x2021],
    },
    HtmlEntityTranslation {
        entity: "&Eacute;",
        codepoints: &[0xC9],
    },
    HtmlEntityTranslation {
        entity: "&Egrave;",
        codepoints: &[0xC8],
    },
    HtmlEntityTranslation {
        entity: "&Iacute;",
        codepoints: &[0xCD],
    },
    HtmlEntityTranslation {
        entity: "&Igrave;",
        codepoints: &[0xCC],
    },
    HtmlEntityTranslation {
        entity: "&Lambda;",
        codepoints: &[0x39B],
    },
    HtmlEntityTranslation {
        entity: "&Ntilde;",
        codepoints: &[0xD1],
    },
    HtmlEntityTranslation {
        entity: "&Oacute;",
        codepoints: &[0xD3],
    },
    HtmlEntityTranslation {
        entity: "&Ograve;",
        codepoints: &[0xD2],
    },
    HtmlEntityTranslation {
        entity: "&Oslash;",
        codepoints: &[0xD8],
    },
    HtmlEntityTranslation {
        entity: "&Otilde;",
        codepoints: &[0xD5],
    },
    HtmlEntityTranslation {
        entity: "&Scaron;",
        codepoints: &[0x160],
    },
    HtmlEntityTranslation {
        entity: "&Uacute;",
        codepoints: &[0xDA],
    },
    HtmlEntityTranslation {
        entity: "&Ugrave;",
        codepoints: &[0xD9],
    },
    HtmlEntityTranslation {
        entity: "&Yacute;",
        codepoints: &[0xDD],
    },
    HtmlEntityTranslation {
        entity: "&aacute;",
        codepoints: &[0xE1],
    },
    HtmlEntityTranslation {
        entity: "&agrave;",
        codepoints: &[0xE0],
    },
    HtmlEntityTranslation {
        entity: "&atilde;",
        codepoints: &[0xE3],
    },
    HtmlEntityTranslation {
        entity: "&brvbar;",
        codepoints: &[0xA6],
    },
    HtmlEntityTranslation {
        entity: "&ccedil;",
        codepoints: &[0xE7],
    },
    HtmlEntityTranslation {
        entity: "&curren;",
        codepoints: &[0xA4],
    },
    HtmlEntityTranslation {
        entity: "&dagger;",
        codepoints: &[0x2020],
    },
    HtmlEntityTranslation {
        entity: "&divide;",
        codepoints: &[0xF7],
    },
    HtmlEntityTranslation {
        entity: "&eacute;",
        codepoints: &[0xE9],
    },
    HtmlEntityTranslation {
        entity: "&egrave;",
        codepoints: &[0xE8],
    },
    HtmlEntityTranslation {
        entity: "&forall;",
        codepoints: &[0x2200],
    },
    HtmlEntityTranslation {
        entity: "&frac12;",
        codepoints: &[0xBD],
    },
    HtmlEntityTranslation {
        entity: "&frac14;",
        codepoints: &[0xBC],
    },
    HtmlEntityTranslation {
        entity: "&frac34;",
        codepoints: &[0xBE],
    },
    HtmlEntityTranslation {
        entity: "&hearts;",
        codepoints: &[0x2665],
    },
    HtmlEntityTranslation {
        entity: "&hellip;",
        codepoints: &[0x2026],
    },
    HtmlEntityTranslation {
        entity: "&iacute;",
        codepoints: &[0xED],
    },
    HtmlEntityTranslation {
        entity: "&igrave;",
        codepoints: &[0xEC],
    },
    HtmlEntityTranslation {
        entity: "&iquest;",
        codepoints: &[0xBF],
    },
    HtmlEntityTranslation {
        entity: "&lambda;",
        codepoints: &[0x3BB],
    },
    HtmlEntityTranslation {
        entity: "&lfloor;",
        codepoints: &[0x230A],
    },
    HtmlEntityTranslation {
        entity: "&lowast;",
        codepoints: &[0x2217],
    },
    HtmlEntityTranslation {
        entity: "&lsaquo;",
        codepoints: &[0x2039],
    },
    HtmlEntityTranslation {
        entity: "&middot;",
        codepoints: &[0xB7],
    },
    HtmlEntityTranslation {
        entity: "&ntilde;",
        codepoints: &[0xF1],
    },
    HtmlEntityTranslation {
        entity: "&oacute;",
        codepoints: &[0xF3],
    },
    HtmlEntityTranslation {
        entity: "&ograve;",
        codepoints: &[0xF2],
    },
    HtmlEntityTranslation {
        entity: "&oslash;",
        codepoints: &[0xF8],
    },
    HtmlEntityTranslation {
        entity: "&otilde;",
        codepoints: &[0xF5],
    },
    HtmlEntityTranslation {
        entity: "&otimes;",
        codepoints: &[0x2297],
    },
    HtmlEntityTranslation {
        entity: "&permil;",
        codepoints: &[0x2030],
    },
    HtmlEntityTranslation {
        entity: "&plusmn;",
        codepoints: &[0xB1],
    },
    HtmlEntityTranslation {
        entity: "&rfloor;",
        codepoints: &[0x230B],
    },
    HtmlEntityTranslation {
        entity: "&rsaquo;",
        codepoints: &[0x203A],
    },
    HtmlEntityTranslation {
        entity: "&scaron;",
        codepoints: &[0x161],
    },
    HtmlEntityTranslation {
        entity: "&sigmaf;",
        codepoints: &[0x3C2],
    },
    HtmlEntityTranslation {
        entity: "&spades;",
        codepoints: &[0x2660],
    },
    HtmlEntityTranslation {
        entity: "&there4;",
        codepoints: &[0x2234],
    },
    HtmlEntityTranslation {
        entity: "&thinsp;",
        codepoints: &[0x2009],
    },
    HtmlEntityTranslation {
        entity: "&uacute;",
        codepoints: &[0xFA],
    },
    HtmlEntityTranslation {
        entity: "&ugrave;",
        codepoints: &[0xF9],
    },
    HtmlEntityTranslation {
        entity: "&weierp;",
        codepoints: &[0x2118],
    },
    HtmlEntityTranslation {
        entity: "&yacute;",
        codepoints: &[0xFD],
    },
    HtmlEntityTranslation {
        entity: "&AElig;",
        codepoints: &[0xC6],
    },
    HtmlEntityTranslation {
        entity: "&Acirc;",
        codepoints: &[0xC2],
    },
    HtmlEntityTranslation {
        entity: "&Alpha;",
        codepoints: &[0x391],
    },
    HtmlEntityTranslation {
        entity: "&Aring;",
        codepoints: &[0xC5],
    },
    HtmlEntityTranslation {
        entity: "&Delta;",
        codepoints: &[0x394],
    },
    HtmlEntityTranslation {
        entity: "&Ecirc;",
        codepoints: &[0xCA],
    },
    HtmlEntityTranslation {
        entity: "&Gamma;",
        codepoints: &[0x393],
    },
    HtmlEntityTranslation {
        entity: "&Icirc;",
        codepoints: &[0xCE],
    },
    HtmlEntityTranslation {
        entity: "&Kappa;",
        codepoints: &[0x39A],
    },
    HtmlEntityTranslation {
        entity: "&OElig;",
        codepoints: &[0x152],
    },
    HtmlEntityTranslation {
        entity: "&Ocirc;",
        codepoints: &[0xD4],
    },
    HtmlEntityTranslation {
        entity: "&Omega;",
        codepoints: &[0x3A9],
    },
    HtmlEntityTranslation {
        entity: "&Prime;",
        codepoints: &[0x2033],
    },
    HtmlEntityTranslation {
        entity: "&Sigma;",
        codepoints: &[0x3A3],
    },
    HtmlEntityTranslation {
        entity: "&THORN;",
        codepoints: &[0xDE],
    },
    HtmlEntityTranslation {
        entity: "&Theta;",
        codepoints: &[0x398],
    },
    HtmlEntityTranslation {
        entity: "&Ucirc;",
        codepoints: &[0xDB],
    },
    HtmlEntityTranslation {
        entity: "&acirc;",
        codepoints: &[0xE2],
    },
    HtmlEntityTranslation {
        entity: "&acute;",
        codepoints: &[0xB4],
    },
    HtmlEntityTranslation {
        entity: "&aelig;",
        codepoints: &[0xE6],
    },
    HtmlEntityTranslation {
        entity: "&alpha;",
        codepoints: &[0x3B1],
    },
    HtmlEntityTranslation {
        entity: "&aring;",
        codepoints: &[0xE5],
    },
    HtmlEntityTranslation {
        entity: "&asymp;",
        codepoints: &[0x2248],
    },
    HtmlEntityTranslation {
        entity: "&bdquo;",
        codepoints: &[0x201E],
    },
    HtmlEntityTranslation {
        entity: "&cedil;",
        codepoints: &[0xB8],
    },
    HtmlEntityTranslation {
        entity: "&clubs;",
        codepoints: &[0x2663],
    },
    HtmlEntityTranslation {
        entity: "&crarr;",
        codepoints: &[0x21B5],
    },
    HtmlEntityTranslation {
        entity: "&delta;",
        codepoints: &[0x3B4],
    },
    HtmlEntityTranslation {
        entity: "&diams;",
        codepoints: &[0x2666],
    },
    HtmlEntityTranslation {
        entity: "&ecirc;",
        codepoints: &[0xEA],
    },
    HtmlEntityTranslation {
        entity: "&empty;",
        codepoints: &[0x2205],
    },
    HtmlEntityTranslation {
        entity: "&equiv;",
        codepoints: &[0x2261],
    },
    HtmlEntityTranslation {
        entity: "&exist;",
        codepoints: &[0x2203],
    },
    HtmlEntityTranslation {
        entity: "&frasl;",
        codepoints: &[0x2044],
    },
    HtmlEntityTranslation {
        entity: "&gamma;",
        codepoints: &[0x3B3],
    },
    HtmlEntityTranslation {
        entity: "&icirc;",
        codepoints: &[0xEE],
    },
    HtmlEntityTranslation {
        entity: "&iexcl;",
        codepoints: &[0xA1],
    },
    HtmlEntityTranslation {
        entity: "&image;",
        codepoints: &[0x2111],
    },
    HtmlEntityTranslation {
        entity: "&infin;",
        codepoints: &[0x221E],
    },
    HtmlEntityTranslation {
        entity: "&kappa;",
        codepoints: &[0x3BA],
    },
    HtmlEntityTranslation {
        entity: "&laquo;",
        codepoints: &[0xAB],
    },
    HtmlEntityTranslation {
        entity: "&lceil;",
        codepoints: &[0x2308],
    },
    HtmlEntityTranslation {
        entity: "&ldquo;",
        codepoints: &[0x201C],
    },
    HtmlEntityTranslation {
        entity: "&lsquo;",
        codepoints: &[0x2018],
    },
    HtmlEntityTranslation {
        entity: "&mdash;",
        codepoints: &[0x2014],
    },
    HtmlEntityTranslation {
        entity: "&micro;",
        codepoints: &[0xB5],
    },
    HtmlEntityTranslation {
        entity: "&minus;",
        codepoints: &[0x2212],
    },
    HtmlEntityTranslation {
        entity: "&nabla;",
        codepoints: &[0x2207],
    },
    HtmlEntityTranslation {
        entity: "&ndash;",
        codepoints: &[0x2013],
    },
    HtmlEntityTranslation {
        entity: "&notin;",
        codepoints: &[0x2209],
    },
    HtmlEntityTranslation {
        entity: "&ocirc;",
        codepoints: &[0xF4],
    },
    HtmlEntityTranslation {
        entity: "&oelig;",
        codepoints: &[0x153],
    },
    HtmlEntityTranslation {
        entity: "&oline;",
        codepoints: &[0x203E],
    },
    HtmlEntityTranslation {
        entity: "&omega;",
        codepoints: &[0x3C9],
    },
    HtmlEntityTranslation {
        entity: "&oplus;",
        codepoints: &[0x2295],
    },
    HtmlEntityTranslation {
        entity: "&pound;",
        codepoints: &[0xA3],
    },
    HtmlEntityTranslation {
        entity: "&prime;",
        codepoints: &[0x2032],
    },
    HtmlEntityTranslation {
        entity: "&radic;",
        codepoints: &[0x221A],
    },
    HtmlEntityTranslation {
        entity: "&raquo;",
        codepoints: &[0xBB],
    },
    HtmlEntityTranslation {
        entity: "&rceil;",
        codepoints: &[0x2309],
    },
    HtmlEntityTranslation {
        entity: "&rdquo;",
        codepoints: &[0x201D],
    },
    HtmlEntityTranslation {
        entity: "&rsquo;",
        codepoints: &[0x2019],
    },
    HtmlEntityTranslation {
        entity: "&sbquo;",
        codepoints: &[0x201A],
    },
    HtmlEntityTranslation {
        entity: "&sigma;",
        codepoints: &[0x3C3],
    },
    HtmlEntityTranslation {
        entity: "&szlig;",
        codepoints: &[0xDF],
    },
    HtmlEntityTranslation {
        entity: "&theta;",
        codepoints: &[0x3B8],
    },
    HtmlEntityTranslation {
        entity: "&thorn;",
        codepoints: &[0xFE],
    },
    HtmlEntityTranslation {
        entity: "&tilde;",
        codepoints: &[0x2DC],
    },
    HtmlEntityTranslation {
        entity: "&times;",
        codepoints: &[0xD7],
    },
    HtmlEntityTranslation {
        entity: "&trade;",
        codepoints: &[0x2122],
    },
    HtmlEntityTranslation {
        entity: "&ucirc;",
        codepoints: &[0xFB],
    },
    HtmlEntityTranslation {
        entity: "&upsih;",
        codepoints: &[0x3D2],
    },
    HtmlEntityTranslation {
        entity: "&#039;",
        codepoints: &[0x27],
    },
    HtmlEntityTranslation {
        entity: "&Auml;",
        codepoints: &[0xC4],
    },
    HtmlEntityTranslation {
        entity: "&Beta;",
        codepoints: &[0x392],
    },
    HtmlEntityTranslation {
        entity: "&Euml;",
        codepoints: &[0xCB],
    },
    HtmlEntityTranslation {
        entity: "&Iota;",
        codepoints: &[0x399],
    },
    HtmlEntityTranslation {
        entity: "&Iuml;",
        codepoints: &[0xCF],
    },
    HtmlEntityTranslation {
        entity: "&Ouml;",
        codepoints: &[0xD6],
    },
    HtmlEntityTranslation {
        entity: "&Uuml;",
        codepoints: &[0xDC],
    },
    HtmlEntityTranslation {
        entity: "&Yuml;",
        codepoints: &[0x178],
    },
    HtmlEntityTranslation {
        entity: "&Zeta;",
        codepoints: &[0x396],
    },
    HtmlEntityTranslation {
        entity: "&auml;",
        codepoints: &[0xE4],
    },
    HtmlEntityTranslation {
        entity: "&beta;",
        codepoints: &[0x3B2],
    },
    HtmlEntityTranslation {
        entity: "&bull;",
        codepoints: &[0x2022],
    },
    HtmlEntityTranslation {
        entity: "&cent;",
        codepoints: &[0xA2],
    },
    HtmlEntityTranslation {
        entity: "&circ;",
        codepoints: &[0x2C6],
    },
    HtmlEntityTranslation {
        entity: "&cong;",
        codepoints: &[0x2245],
    },
    HtmlEntityTranslation {
        entity: "&copy;",
        codepoints: &[0xA9],
    },
    HtmlEntityTranslation {
        entity: "&dArr;",
        codepoints: &[0x21D3],
    },
    HtmlEntityTranslation {
        entity: "&darr;",
        codepoints: &[0x2193],
    },
    HtmlEntityTranslation {
        entity: "&emsp;",
        codepoints: &[0x2003],
    },
    HtmlEntityTranslation {
        entity: "&ensp;",
        codepoints: &[0x2002],
    },
    HtmlEntityTranslation {
        entity: "&euml;",
        codepoints: &[0xEB],
    },
    HtmlEntityTranslation {
        entity: "&euro;",
        codepoints: &[0x20AC],
    },
    HtmlEntityTranslation {
        entity: "&fnof;",
        codepoints: &[0x192],
    },
    HtmlEntityTranslation {
        entity: "&hArr;",
        codepoints: &[0x21D4],
    },
    HtmlEntityTranslation {
        entity: "&harr;",
        codepoints: &[0x2194],
    },
    HtmlEntityTranslation {
        entity: "&iota;",
        codepoints: &[0x3B9],
    },
    HtmlEntityTranslation {
        entity: "&isin;",
        codepoints: &[0x2208],
    },
    HtmlEntityTranslation {
        entity: "&iuml;",
        codepoints: &[0xEF],
    },
    HtmlEntityTranslation {
        entity: "&lArr;",
        codepoints: &[0x21D0],
    },
    HtmlEntityTranslation {
        entity: "&lang;",
        codepoints: &[0x2329],
    },
    HtmlEntityTranslation {
        entity: "&larr;",
        codepoints: &[0x2190],
    },
    HtmlEntityTranslation {
        entity: "&macr;",
        codepoints: &[0xAF],
    },
    HtmlEntityTranslation {
        entity: "&nbsp;",
        codepoints: &[0xA0],
    },
    HtmlEntityTranslation {
        entity: "&nsub;",
        codepoints: &[0x2284],
    },
    HtmlEntityTranslation {
        entity: "&ordf;",
        codepoints: &[0xAA],
    },
    HtmlEntityTranslation {
        entity: "&ordm;",
        codepoints: &[0xBA],
    },
    HtmlEntityTranslation {
        entity: "&ouml;",
        codepoints: &[0xF6],
    },
    HtmlEntityTranslation {
        entity: "&para;",
        codepoints: &[0xB6],
    },
    HtmlEntityTranslation {
        entity: "&part;",
        codepoints: &[0x2202],
    },
    HtmlEntityTranslation {
        entity: "&perp;",
        codepoints: &[0x22A5],
    },
    HtmlEntityTranslation {
        entity: "&prod;",
        codepoints: &[0x220F],
    },
    HtmlEntityTranslation {
        entity: "&prop;",
        codepoints: &[0x221D],
    },
    HtmlEntityTranslation {
        entity: "&quot;",
        codepoints: &[0x22],
    },
    HtmlEntityTranslation {
        entity: "&rArr;",
        codepoints: &[0x21D2],
    },
    HtmlEntityTranslation {
        entity: "&rang;",
        codepoints: &[0x232A],
    },
    HtmlEntityTranslation {
        entity: "&rarr;",
        codepoints: &[0x2192],
    },
    HtmlEntityTranslation {
        entity: "&real;",
        codepoints: &[0x211C],
    },
    HtmlEntityTranslation {
        entity: "&sdot;",
        codepoints: &[0x22C5],
    },
    HtmlEntityTranslation {
        entity: "&sect;",
        codepoints: &[0xA7],
    },
    HtmlEntityTranslation {
        entity: "&sube;",
        codepoints: &[0x2286],
    },
    HtmlEntityTranslation {
        entity: "&sup1;",
        codepoints: &[0xB9],
    },
    HtmlEntityTranslation {
        entity: "&sup2;",
        codepoints: &[0xB2],
    },
    HtmlEntityTranslation {
        entity: "&sup3;",
        codepoints: &[0xB3],
    },
    HtmlEntityTranslation {
        entity: "&supe;",
        codepoints: &[0x2287],
    },
    HtmlEntityTranslation {
        entity: "&uArr;",
        codepoints: &[0x21D1],
    },
    HtmlEntityTranslation {
        entity: "&uarr;",
        codepoints: &[0x2191],
    },
    HtmlEntityTranslation {
        entity: "&uuml;",
        codepoints: &[0xFC],
    },
    HtmlEntityTranslation {
        entity: "&yuml;",
        codepoints: &[0xFF],
    },
    HtmlEntityTranslation {
        entity: "&zeta;",
        codepoints: &[0x3B6],
    },
    HtmlEntityTranslation {
        entity: "&zwnj;",
        codepoints: &[0x200C],
    },
    HtmlEntityTranslation {
        entity: "&Chi;",
        codepoints: &[0x3A7],
    },
    HtmlEntityTranslation {
        entity: "&ETH;",
        codepoints: &[0xD0],
    },
    HtmlEntityTranslation {
        entity: "&Eta;",
        codepoints: &[0x397],
    },
    HtmlEntityTranslation {
        entity: "&Phi;",
        codepoints: &[0x3A6],
    },
    HtmlEntityTranslation {
        entity: "&Psi;",
        codepoints: &[0x3A8],
    },
    HtmlEntityTranslation {
        entity: "&Rho;",
        codepoints: &[0x3A1],
    },
    HtmlEntityTranslation {
        entity: "&Tau;",
        codepoints: &[0x3A4],
    },
    HtmlEntityTranslation {
        entity: "&amp;",
        codepoints: &[0x26],
    },
    HtmlEntityTranslation {
        entity: "&and;",
        codepoints: &[0x2227],
    },
    HtmlEntityTranslation {
        entity: "&ang;",
        codepoints: &[0x2220],
    },
    HtmlEntityTranslation {
        entity: "&cap;",
        codepoints: &[0x2229],
    },
    HtmlEntityTranslation {
        entity: "&chi;",
        codepoints: &[0x3C7],
    },
    HtmlEntityTranslation {
        entity: "&cup;",
        codepoints: &[0x222A],
    },
    HtmlEntityTranslation {
        entity: "&deg;",
        codepoints: &[0xB0],
    },
    HtmlEntityTranslation {
        entity: "&eta;",
        codepoints: &[0x3B7],
    },
    HtmlEntityTranslation {
        entity: "&eth;",
        codepoints: &[0xF0],
    },
    HtmlEntityTranslation {
        entity: "&int;",
        codepoints: &[0x222B],
    },
    HtmlEntityTranslation {
        entity: "&loz;",
        codepoints: &[0x25CA],
    },
    HtmlEntityTranslation {
        entity: "&lrm;",
        codepoints: &[0x200E],
    },
    HtmlEntityTranslation {
        entity: "&not;",
        codepoints: &[0xAC],
    },
    HtmlEntityTranslation {
        entity: "&phi;",
        codepoints: &[0x3C6],
    },
    HtmlEntityTranslation {
        entity: "&piv;",
        codepoints: &[0x3D6],
    },
    HtmlEntityTranslation {
        entity: "&psi;",
        codepoints: &[0x3C8],
    },
    HtmlEntityTranslation {
        entity: "&reg;",
        codepoints: &[0xAE],
    },
    HtmlEntityTranslation {
        entity: "&rho;",
        codepoints: &[0x3C1],
    },
    HtmlEntityTranslation {
        entity: "&rlm;",
        codepoints: &[0x200F],
    },
    HtmlEntityTranslation {
        entity: "&shy;",
        codepoints: &[0xAD],
    },
    HtmlEntityTranslation {
        entity: "&sim;",
        codepoints: &[0x223C],
    },
    HtmlEntityTranslation {
        entity: "&sub;",
        codepoints: &[0x2282],
    },
    HtmlEntityTranslation {
        entity: "&sum;",
        codepoints: &[0x2211],
    },
    HtmlEntityTranslation {
        entity: "&sup;",
        codepoints: &[0x2283],
    },
    HtmlEntityTranslation {
        entity: "&tau;",
        codepoints: &[0x3C4],
    },
    HtmlEntityTranslation {
        entity: "&uml;",
        codepoints: &[0xA8],
    },
    HtmlEntityTranslation {
        entity: "&yen;",
        codepoints: &[0xA5],
    },
    HtmlEntityTranslation {
        entity: "&zwj;",
        codepoints: &[0x200D],
    },
    HtmlEntityTranslation {
        entity: "&Mu;",
        codepoints: &[0x39C],
    },
    HtmlEntityTranslation {
        entity: "&Nu;",
        codepoints: &[0x39D],
    },
    HtmlEntityTranslation {
        entity: "&Pi;",
        codepoints: &[0x3A0],
    },
    HtmlEntityTranslation {
        entity: "&Xi;",
        codepoints: &[0x39E],
    },
    HtmlEntityTranslation {
        entity: "&ge;",
        codepoints: &[0x2265],
    },
    HtmlEntityTranslation {
        entity: "&gt;",
        codepoints: &[0x3E],
    },
    HtmlEntityTranslation {
        entity: "&le;",
        codepoints: &[0x2264],
    },
    HtmlEntityTranslation {
        entity: "&lt;",
        codepoints: &[0x3C],
    },
    HtmlEntityTranslation {
        entity: "&mu;",
        codepoints: &[0x3BC],
    },
    HtmlEntityTranslation {
        entity: "&ne;",
        codepoints: &[0x2260],
    },
    HtmlEntityTranslation {
        entity: "&ni;",
        codepoints: &[0x220B],
    },
    HtmlEntityTranslation {
        entity: "&nu;",
        codepoints: &[0x3BD],
    },
    HtmlEntityTranslation {
        entity: "&or;",
        codepoints: &[0x2228],
    },
    HtmlEntityTranslation {
        entity: "&pi;",
        codepoints: &[0x3C0],
    },
    HtmlEntityTranslation {
        entity: "&xi;",
        codepoints: &[0x3BE],
    },
];
pub static HTML4_SINGLE_BYTE_EXTRA_ENTITIES: &[HtmlEntityTranslation] = &[
    HtmlEntityTranslation {
        entity: "&Zcaron;",
        codepoints: &[0x17D],
    },
    HtmlEntityTranslation {
        entity: "&zcaron;",
        codepoints: &[0x17E],
    },
];

pub static ISO_8859_1_CODEPOINTS: &[(u8, u32)] = &[
    (0xA0, 0xA0),
    (0xA1, 0xA1),
    (0xA2, 0xA2),
    (0xA3, 0xA3),
    (0xA4, 0xA4),
    (0xA5, 0xA5),
    (0xA6, 0xA6),
    (0xA7, 0xA7),
    (0xA8, 0xA8),
    (0xA9, 0xA9),
    (0xAA, 0xAA),
    (0xAB, 0xAB),
    (0xAC, 0xAC),
    (0xAD, 0xAD),
    (0xAE, 0xAE),
    (0xAF, 0xAF),
    (0xB0, 0xB0),
    (0xB1, 0xB1),
    (0xB2, 0xB2),
    (0xB3, 0xB3),
    (0xB4, 0xB4),
    (0xB5, 0xB5),
    (0xB6, 0xB6),
    (0xB7, 0xB7),
    (0xB8, 0xB8),
    (0xB9, 0xB9),
    (0xBA, 0xBA),
    (0xBB, 0xBB),
    (0xBC, 0xBC),
    (0xBD, 0xBD),
    (0xBE, 0xBE),
    (0xBF, 0xBF),
    (0xC0, 0xC0),
    (0xC1, 0xC1),
    (0xC2, 0xC2),
    (0xC3, 0xC3),
    (0xC4, 0xC4),
    (0xC5, 0xC5),
    (0xC6, 0xC6),
    (0xC7, 0xC7),
    (0xC8, 0xC8),
    (0xC9, 0xC9),
    (0xCA, 0xCA),
    (0xCB, 0xCB),
    (0xCC, 0xCC),
    (0xCD, 0xCD),
    (0xCE, 0xCE),
    (0xCF, 0xCF),
    (0xD0, 0xD0),
    (0xD1, 0xD1),
    (0xD2, 0xD2),
    (0xD3, 0xD3),
    (0xD4, 0xD4),
    (0xD5, 0xD5),
    (0xD6, 0xD6),
    (0xD7, 0xD7),
    (0xD8, 0xD8),
    (0xD9, 0xD9),
    (0xDA, 0xDA),
    (0xDB, 0xDB),
    (0xDC, 0xDC),
    (0xDD, 0xDD),
    (0xDE, 0xDE),
    (0xDF, 0xDF),
    (0xE0, 0xE0),
    (0xE1, 0xE1),
    (0xE2, 0xE2),
    (0xE3, 0xE3),
    (0xE4, 0xE4),
    (0xE5, 0xE5),
    (0xE6, 0xE6),
    (0xE7, 0xE7),
    (0xE8, 0xE8),
    (0xE9, 0xE9),
    (0xEA, 0xEA),
    (0xEB, 0xEB),
    (0xEC, 0xEC),
    (0xED, 0xED),
    (0xEE, 0xEE),
    (0xEF, 0xEF),
    (0xF0, 0xF0),
    (0xF1, 0xF1),
    (0xF2, 0xF2),
    (0xF3, 0xF3),
    (0xF4, 0xF4),
    (0xF5, 0xF5),
    (0xF6, 0xF6),
    (0xF7, 0xF7),
    (0xF8, 0xF8),
    (0xF9, 0xF9),
    (0xFA, 0xFA),
    (0xFB, 0xFB),
    (0xFC, 0xFC),
    (0xFD, 0xFD),
    (0xFE, 0xFE),
    (0xFF, 0xFF),
];
pub static ISO_8859_5_CODEPOINTS: &[(u8, u32)] = &[
    (0x80, 0x80),
    (0x81, 0x81),
    (0x82, 0x82),
    (0x83, 0x83),
    (0x84, 0x84),
    (0x85, 0x85),
    (0x86, 0x86),
    (0x87, 0x87),
    (0x88, 0x88),
    (0x89, 0x89),
    (0x8A, 0x8A),
    (0x8B, 0x8B),
    (0x8C, 0x8C),
    (0x8D, 0x8D),
    (0x8E, 0x8E),
    (0x8F, 0x8F),
    (0x90, 0x90),
    (0x91, 0x91),
    (0x92, 0x92),
    (0x93, 0x93),
    (0x94, 0x94),
    (0x95, 0x95),
    (0x96, 0x96),
    (0x97, 0x97),
    (0x98, 0x98),
    (0x99, 0x99),
    (0x9A, 0x9A),
    (0x9B, 0x9B),
    (0x9C, 0x9C),
    (0x9D, 0x9D),
    (0x9E, 0x9E),
    (0x9F, 0x9F),
    (0xA0, 0xA0),
    (0xA1, 0x401),
    (0xA2, 0x402),
    (0xA3, 0x403),
    (0xA4, 0x404),
    (0xA5, 0x405),
    (0xA6, 0x406),
    (0xA7, 0x407),
    (0xA8, 0x408),
    (0xA9, 0x409),
    (0xAA, 0x40A),
    (0xAB, 0x40B),
    (0xAC, 0x40C),
    (0xAD, 0xAD),
    (0xAE, 0x40E),
    (0xAF, 0x40F),
    (0xB0, 0x410),
    (0xB1, 0x411),
    (0xB2, 0x412),
    (0xB3, 0x413),
    (0xB4, 0x414),
    (0xB5, 0x415),
    (0xB6, 0x416),
    (0xB7, 0x417),
    (0xB8, 0x418),
    (0xB9, 0x419),
    (0xBA, 0x41A),
    (0xBB, 0x41B),
    (0xBC, 0x41C),
    (0xBD, 0x41D),
    (0xBE, 0x41E),
    (0xBF, 0x41F),
    (0xC0, 0x420),
    (0xC1, 0x421),
    (0xC2, 0x422),
    (0xC3, 0x423),
    (0xC4, 0x424),
    (0xC5, 0x425),
    (0xC6, 0x426),
    (0xC7, 0x427),
    (0xC8, 0x428),
    (0xC9, 0x429),
    (0xCA, 0x42A),
    (0xCB, 0x42B),
    (0xCC, 0x42C),
    (0xCD, 0x42D),
    (0xCE, 0x42E),
    (0xCF, 0x42F),
    (0xD0, 0x430),
    (0xD1, 0x431),
    (0xD2, 0x432),
    (0xD3, 0x433),
    (0xD4, 0x434),
    (0xD5, 0x435),
    (0xD6, 0x436),
    (0xD7, 0x437),
    (0xD8, 0x438),
    (0xD9, 0x439),
    (0xDA, 0x43A),
    (0xDB, 0x43B),
    (0xDC, 0x43C),
    (0xDD, 0x43D),
    (0xDE, 0x43E),
    (0xDF, 0x43F),
    (0xE0, 0x440),
    (0xE1, 0x441),
    (0xE2, 0x442),
    (0xE3, 0x443),
    (0xE4, 0x444),
    (0xE5, 0x445),
    (0xE6, 0x446),
    (0xE7, 0x447),
    (0xE8, 0x448),
    (0xE9, 0x449),
    (0xEA, 0x44A),
    (0xEB, 0x44B),
    (0xEC, 0x44C),
    (0xED, 0x44D),
    (0xEE, 0x44E),
    (0xEF, 0x44F),
    (0xF0, 0x2116),
    (0xF1, 0x451),
    (0xF2, 0x452),
    (0xF3, 0x453),
    (0xF4, 0x454),
    (0xF5, 0x455),
    (0xF6, 0x456),
    (0xF7, 0x457),
    (0xF8, 0x458),
    (0xF9, 0x459),
    (0xFA, 0x45A),
    (0xFB, 0x45B),
    (0xFC, 0x45C),
    (0xFD, 0xA7),
    (0xFE, 0x45E),
    (0xFF, 0x45F),
];
pub static ISO_8859_15_CODEPOINTS: &[(u8, u32)] = &[
    (0x80, 0x80),
    (0x81, 0x81),
    (0x82, 0x82),
    (0x83, 0x83),
    (0x84, 0x84),
    (0x85, 0x85),
    (0x86, 0x86),
    (0x87, 0x87),
    (0x88, 0x88),
    (0x89, 0x89),
    (0x8A, 0x8A),
    (0x8B, 0x8B),
    (0x8C, 0x8C),
    (0x8D, 0x8D),
    (0x8E, 0x8E),
    (0x8F, 0x8F),
    (0x90, 0x90),
    (0x91, 0x91),
    (0x92, 0x92),
    (0x93, 0x93),
    (0x94, 0x94),
    (0x95, 0x95),
    (0x96, 0x96),
    (0x97, 0x97),
    (0x98, 0x98),
    (0x99, 0x99),
    (0x9A, 0x9A),
    (0x9B, 0x9B),
    (0x9C, 0x9C),
    (0x9D, 0x9D),
    (0x9E, 0x9E),
    (0x9F, 0x9F),
    (0xA0, 0xA0),
    (0xA1, 0xA1),
    (0xA2, 0xA2),
    (0xA3, 0xA3),
    (0xA4, 0x20AC),
    (0xA5, 0xA5),
    (0xA6, 0x160),
    (0xA7, 0xA7),
    (0xA8, 0x161),
    (0xA9, 0xA9),
    (0xAA, 0xAA),
    (0xAB, 0xAB),
    (0xAC, 0xAC),
    (0xAD, 0xAD),
    (0xAE, 0xAE),
    (0xAF, 0xAF),
    (0xB0, 0xB0),
    (0xB1, 0xB1),
    (0xB2, 0xB2),
    (0xB3, 0xB3),
    (0xB4, 0x17D),
    (0xB5, 0xB5),
    (0xB6, 0xB6),
    (0xB7, 0xB7),
    (0xB8, 0x17E),
    (0xB9, 0xB9),
    (0xBA, 0xBA),
    (0xBB, 0xBB),
    (0xBC, 0x152),
    (0xBD, 0x153),
    (0xBE, 0x178),
    (0xBF, 0xBF),
    (0xC0, 0xC0),
    (0xC1, 0xC1),
    (0xC2, 0xC2),
    (0xC3, 0xC3),
    (0xC4, 0xC4),
    (0xC5, 0xC5),
    (0xC6, 0xC6),
    (0xC7, 0xC7),
    (0xC8, 0xC8),
    (0xC9, 0xC9),
    (0xCA, 0xCA),
    (0xCB, 0xCB),
    (0xCC, 0xCC),
    (0xCD, 0xCD),
    (0xCE, 0xCE),
    (0xCF, 0xCF),
    (0xD0, 0xD0),
    (0xD1, 0xD1),
    (0xD2, 0xD2),
    (0xD3, 0xD3),
    (0xD4, 0xD4),
    (0xD5, 0xD5),
    (0xD6, 0xD6),
    (0xD7, 0xD7),
    (0xD8, 0xD8),
    (0xD9, 0xD9),
    (0xDA, 0xDA),
    (0xDB, 0xDB),
    (0xDC, 0xDC),
    (0xDD, 0xDD),
    (0xDE, 0xDE),
    (0xDF, 0xDF),
    (0xE0, 0xE0),
    (0xE1, 0xE1),
    (0xE2, 0xE2),
    (0xE3, 0xE3),
    (0xE4, 0xE4),
    (0xE5, 0xE5),
    (0xE6, 0xE6),
    (0xE7, 0xE7),
    (0xE8, 0xE8),
    (0xE9, 0xE9),
    (0xEA, 0xEA),
    (0xEB, 0xEB),
    (0xEC, 0xEC),
    (0xED, 0xED),
    (0xEE, 0xEE),
    (0xEF, 0xEF),
    (0xF0, 0xF0),
    (0xF1, 0xF1),
    (0xF2, 0xF2),
    (0xF3, 0xF3),
    (0xF4, 0xF4),
    (0xF5, 0xF5),
    (0xF6, 0xF6),
    (0xF7, 0xF7),
    (0xF8, 0xF8),
    (0xF9, 0xF9),
    (0xFA, 0xFA),
    (0xFB, 0xFB),
    (0xFC, 0xFC),
    (0xFD, 0xFD),
    (0xFE, 0xFE),
    (0xFF, 0xFF),
];
pub static CP1251_CODEPOINTS: &[(u8, u32)] = &[
    (0x80, 0x402),
    (0x81, 0x403),
    (0x82, 0x201A),
    (0x83, 0x453),
    (0x84, 0x201E),
    (0x85, 0x2026),
    (0x86, 0x2020),
    (0x87, 0x2021),
    (0x88, 0x20AC),
    (0x89, 0x2030),
    (0x8A, 0x409),
    (0x8B, 0x2039),
    (0x8C, 0x40A),
    (0x8D, 0x40C),
    (0x8E, 0x40B),
    (0x8F, 0x40F),
    (0x90, 0x452),
    (0x91, 0x2018),
    (0x92, 0x2019),
    (0x93, 0x201C),
    (0x94, 0x201D),
    (0x95, 0x2022),
    (0x96, 0x2013),
    (0x97, 0x2014),
    (0x99, 0x2122),
    (0x9A, 0x459),
    (0x9B, 0x203A),
    (0x9C, 0x45A),
    (0x9D, 0x45C),
    (0x9E, 0x45B),
    (0x9F, 0x45F),
    (0xA0, 0xA0),
    (0xA1, 0x40E),
    (0xA2, 0x45E),
    (0xA3, 0x408),
    (0xA4, 0xA4),
    (0xA5, 0x490),
    (0xA6, 0xA6),
    (0xA7, 0xA7),
    (0xA8, 0x401),
    (0xA9, 0xA9),
    (0xAA, 0x404),
    (0xAB, 0xAB),
    (0xAC, 0xAC),
    (0xAD, 0xAD),
    (0xAE, 0xAE),
    (0xAF, 0x407),
    (0xB0, 0xB0),
    (0xB1, 0xB1),
    (0xB2, 0x406),
    (0xB3, 0x456),
    (0xB4, 0x491),
    (0xB5, 0xB5),
    (0xB6, 0xB6),
    (0xB7, 0xB7),
    (0xB8, 0x451),
    (0xB9, 0x2116),
    (0xBA, 0x454),
    (0xBB, 0xBB),
    (0xBC, 0x458),
    (0xBD, 0x405),
    (0xBE, 0x455),
    (0xBF, 0x457),
    (0xC0, 0x410),
    (0xC1, 0x411),
    (0xC2, 0x412),
    (0xC3, 0x413),
    (0xC4, 0x414),
    (0xC5, 0x415),
    (0xC6, 0x416),
    (0xC7, 0x417),
    (0xC8, 0x418),
    (0xC9, 0x419),
    (0xCA, 0x41A),
    (0xCB, 0x41B),
    (0xCC, 0x41C),
    (0xCD, 0x41D),
    (0xCE, 0x41E),
    (0xCF, 0x41F),
    (0xD0, 0x420),
    (0xD1, 0x421),
    (0xD2, 0x422),
    (0xD3, 0x423),
    (0xD4, 0x424),
    (0xD5, 0x425),
    (0xD6, 0x426),
    (0xD7, 0x427),
    (0xD8, 0x428),
    (0xD9, 0x429),
    (0xDA, 0x42A),
    (0xDB, 0x42B),
    (0xDC, 0x42C),
    (0xDD, 0x42D),
    (0xDE, 0x42E),
    (0xDF, 0x42F),
    (0xE0, 0x430),
    (0xE1, 0x431),
    (0xE2, 0x432),
    (0xE3, 0x433),
    (0xE4, 0x434),
    (0xE5, 0x435),
    (0xE6, 0x436),
    (0xE7, 0x437),
    (0xE8, 0x438),
    (0xE9, 0x439),
    (0xEA, 0x43A),
    (0xEB, 0x43B),
    (0xEC, 0x43C),
    (0xED, 0x43D),
    (0xEE, 0x43E),
    (0xEF, 0x43F),
    (0xF0, 0x440),
    (0xF1, 0x441),
    (0xF2, 0x442),
    (0xF3, 0x443),
    (0xF4, 0x444),
    (0xF5, 0x445),
    (0xF6, 0x446),
    (0xF7, 0x447),
    (0xF8, 0x448),
    (0xF9, 0x449),
    (0xFA, 0x44A),
    (0xFB, 0x44B),
    (0xFC, 0x44C),
    (0xFD, 0x44D),
    (0xFE, 0x44E),
    (0xFF, 0x44F),
];
pub static CP1252_CODEPOINTS: &[(u8, u32)] = &[
    (0x80, 0x20AC),
    (0x82, 0x201A),
    (0x83, 0x192),
    (0x84, 0x201E),
    (0x85, 0x2026),
    (0x86, 0x2020),
    (0x87, 0x2021),
    (0x88, 0x2C6),
    (0x89, 0x2030),
    (0x8A, 0x160),
    (0x8B, 0x2039),
    (0x8C, 0x152),
    (0x8E, 0x17D),
    (0x91, 0x2018),
    (0x92, 0x2019),
    (0x93, 0x201C),
    (0x94, 0x201D),
    (0x95, 0x2022),
    (0x96, 0x2013),
    (0x97, 0x2014),
    (0x98, 0x2DC),
    (0x99, 0x2122),
    (0x9A, 0x161),
    (0x9B, 0x203A),
    (0x9C, 0x153),
    (0x9E, 0x17E),
    (0x9F, 0x178),
    (0xA0, 0xA0),
    (0xA1, 0xA1),
    (0xA2, 0xA2),
    (0xA3, 0xA3),
    (0xA4, 0xA4),
    (0xA5, 0xA5),
    (0xA6, 0xA6),
    (0xA7, 0xA7),
    (0xA8, 0xA8),
    (0xA9, 0xA9),
    (0xAA, 0xAA),
    (0xAB, 0xAB),
    (0xAC, 0xAC),
    (0xAD, 0xAD),
    (0xAE, 0xAE),
    (0xAF, 0xAF),
    (0xB0, 0xB0),
    (0xB1, 0xB1),
    (0xB2, 0xB2),
    (0xB3, 0xB3),
    (0xB4, 0xB4),
    (0xB5, 0xB5),
    (0xB6, 0xB6),
    (0xB7, 0xB7),
    (0xB8, 0xB8),
    (0xB9, 0xB9),
    (0xBA, 0xBA),
    (0xBB, 0xBB),
    (0xBC, 0xBC),
    (0xBD, 0xBD),
    (0xBE, 0xBE),
    (0xBF, 0xBF),
    (0xC0, 0xC0),
    (0xC1, 0xC1),
    (0xC2, 0xC2),
    (0xC3, 0xC3),
    (0xC4, 0xC4),
    (0xC5, 0xC5),
    (0xC6, 0xC6),
    (0xC7, 0xC7),
    (0xC8, 0xC8),
    (0xC9, 0xC9),
    (0xCA, 0xCA),
    (0xCB, 0xCB),
    (0xCC, 0xCC),
    (0xCD, 0xCD),
    (0xCE, 0xCE),
    (0xCF, 0xCF),
    (0xD0, 0xD0),
    (0xD1, 0xD1),
    (0xD2, 0xD2),
    (0xD3, 0xD3),
    (0xD4, 0xD4),
    (0xD5, 0xD5),
    (0xD6, 0xD6),
    (0xD7, 0xD7),
    (0xD8, 0xD8),
    (0xD9, 0xD9),
    (0xDA, 0xDA),
    (0xDB, 0xDB),
    (0xDC, 0xDC),
    (0xDD, 0xDD),
    (0xDE, 0xDE),
    (0xDF, 0xDF),
    (0xE0, 0xE0),
    (0xE1, 0xE1),
    (0xE2, 0xE2),
    (0xE3, 0xE3),
    (0xE4, 0xE4),
    (0xE5, 0xE5),
    (0xE6, 0xE6),
    (0xE7, 0xE7),
    (0xE8, 0xE8),
    (0xE9, 0xE9),
    (0xEA, 0xEA),
    (0xEB, 0xEB),
    (0xEC, 0xEC),
    (0xED, 0xED),
    (0xEE, 0xEE),
    (0xEF, 0xEF),
    (0xF0, 0xF0),
    (0xF1, 0xF1),
    (0xF2, 0xF2),
    (0xF3, 0xF3),
    (0xF4, 0xF4),
    (0xF5, 0xF5),
    (0xF6, 0xF6),
    (0xF7, 0xF7),
    (0xF8, 0xF8),
    (0xF9, 0xF9),
    (0xFA, 0xFA),
    (0xFB, 0xFB),
    (0xFC, 0xFC),
    (0xFD, 0xFD),
    (0xFE, 0xFE),
    (0xFF, 0xFF),
];
pub static CP866_CODEPOINTS: &[(u8, u32)] = &[
    (0x80, 0x410),
    (0x81, 0x411),
    (0x82, 0x412),
    (0x83, 0x413),
    (0x84, 0x414),
    (0x85, 0x415),
    (0x86, 0x416),
    (0x87, 0x417),
    (0x88, 0x418),
    (0x89, 0x419),
    (0x8A, 0x41A),
    (0x8B, 0x41B),
    (0x8C, 0x41C),
    (0x8D, 0x41D),
    (0x8E, 0x41E),
    (0x8F, 0x41F),
    (0x90, 0x420),
    (0x91, 0x421),
    (0x92, 0x422),
    (0x93, 0x423),
    (0x94, 0x424),
    (0x95, 0x425),
    (0x96, 0x426),
    (0x97, 0x427),
    (0x98, 0x428),
    (0x99, 0x429),
    (0x9A, 0x42A),
    (0x9B, 0x42B),
    (0x9C, 0x42C),
    (0x9D, 0x42D),
    (0x9E, 0x42E),
    (0x9F, 0x42F),
    (0xA0, 0x430),
    (0xA1, 0x431),
    (0xA2, 0x432),
    (0xA3, 0x433),
    (0xA4, 0x434),
    (0xA5, 0x435),
    (0xA6, 0x436),
    (0xA7, 0x437),
    (0xA8, 0x438),
    (0xA9, 0x439),
    (0xAA, 0x43A),
    (0xAB, 0x43B),
    (0xAC, 0x43C),
    (0xAD, 0x43D),
    (0xAE, 0x43E),
    (0xAF, 0x43F),
    (0xB0, 0x2591),
    (0xB1, 0x2592),
    (0xB2, 0x2593),
    (0xB3, 0x2502),
    (0xB4, 0x2524),
    (0xB5, 0x2561),
    (0xB6, 0x2562),
    (0xB7, 0x2556),
    (0xB8, 0x2555),
    (0xB9, 0x2563),
    (0xBA, 0x2551),
    (0xBB, 0x2557),
    (0xBC, 0x255D),
    (0xBD, 0x255C),
    (0xBE, 0x255B),
    (0xBF, 0x2510),
    (0xC0, 0x2514),
    (0xC1, 0x2534),
    (0xC2, 0x252C),
    (0xC3, 0x251C),
    (0xC4, 0x2500),
    (0xC5, 0x253C),
    (0xC6, 0x255E),
    (0xC7, 0x255F),
    (0xC8, 0x255A),
    (0xC9, 0x2554),
    (0xCA, 0x2569),
    (0xCB, 0x2566),
    (0xCC, 0x2560),
    (0xCD, 0x2550),
    (0xCE, 0x256C),
    (0xCF, 0x2567),
    (0xD0, 0x2568),
    (0xD1, 0x2564),
    (0xD2, 0x2565),
    (0xD3, 0x2559),
    (0xD4, 0x2558),
    (0xD5, 0x2552),
    (0xD6, 0x2553),
    (0xD7, 0x256B),
    (0xD8, 0x256A),
    (0xD9, 0x2518),
    (0xDA, 0x250C),
    (0xDB, 0x2588),
    (0xDC, 0x2584),
    (0xDD, 0x258C),
    (0xDE, 0x2590),
    (0xDF, 0x2580),
    (0xE0, 0x440),
    (0xE1, 0x441),
    (0xE2, 0x442),
    (0xE3, 0x443),
    (0xE4, 0x444),
    (0xE5, 0x445),
    (0xE6, 0x446),
    (0xE7, 0x447),
    (0xE8, 0x448),
    (0xE9, 0x449),
    (0xEA, 0x44A),
    (0xEB, 0x44B),
    (0xEC, 0x44C),
    (0xED, 0x44D),
    (0xEE, 0x44E),
    (0xEF, 0x44F),
    (0xF0, 0x401),
    (0xF1, 0x451),
    (0xF2, 0x404),
    (0xF3, 0x454),
    (0xF4, 0x407),
    (0xF5, 0x457),
    (0xF6, 0x40E),
    (0xF7, 0x45E),
    (0xF8, 0xB0),
    (0xF9, 0x2219),
    (0xFA, 0xB7),
    (0xFB, 0x221A),
    (0xFC, 0x2116),
    (0xFD, 0xA4),
    (0xFE, 0x25A0),
    (0xFF, 0xA0),
];
pub static KOI8_R_CODEPOINTS: &[(u8, u32)] = &[
    (0x80, 0x2500),
    (0x81, 0x2502),
    (0x82, 0x250C),
    (0x83, 0x2510),
    (0x84, 0x2514),
    (0x85, 0x2518),
    (0x86, 0x251C),
    (0x87, 0x2524),
    (0x88, 0x252C),
    (0x89, 0x2534),
    (0x8A, 0x253C),
    (0x8B, 0x2580),
    (0x8C, 0x2584),
    (0x8D, 0x2588),
    (0x8E, 0x258C),
    (0x8F, 0x2590),
    (0x90, 0x2591),
    (0x91, 0x2592),
    (0x92, 0x2593),
    (0x93, 0x2320),
    (0x94, 0x25A0),
    (0x95, 0x2219),
    (0x96, 0x221A),
    (0x97, 0x2248),
    (0x98, 0x2264),
    (0x99, 0x2265),
    (0x9A, 0xA0),
    (0x9B, 0x2321),
    (0x9C, 0xB0),
    (0x9D, 0xB2),
    (0x9E, 0xB7),
    (0x9F, 0xF7),
    (0xA0, 0x2550),
    (0xA1, 0x2551),
    (0xA2, 0x2552),
    (0xA3, 0x451),
    (0xA4, 0x2553),
    (0xA5, 0x2554),
    (0xA6, 0x2555),
    (0xA7, 0x2556),
    (0xA8, 0x2557),
    (0xA9, 0x2558),
    (0xAA, 0x2559),
    (0xAB, 0x255A),
    (0xAC, 0x255B),
    (0xAD, 0x255C),
    (0xAE, 0x255D),
    (0xAF, 0x255E),
    (0xB0, 0x255F),
    (0xB1, 0x2560),
    (0xB2, 0x2561),
    (0xB3, 0x401),
    (0xB4, 0x2562),
    (0xB5, 0x2563),
    (0xB6, 0x2564),
    (0xB7, 0x2565),
    (0xB8, 0x2566),
    (0xB9, 0x2567),
    (0xBA, 0x2568),
    (0xBB, 0x2569),
    (0xBC, 0x256A),
    (0xBD, 0x256B),
    (0xBE, 0x256C),
    (0xBF, 0xA9),
    (0xC0, 0x44E),
    (0xC1, 0x430),
    (0xC2, 0x431),
    (0xC3, 0x446),
    (0xC4, 0x434),
    (0xC5, 0x435),
    (0xC6, 0x444),
    (0xC7, 0x433),
    (0xC8, 0x445),
    (0xC9, 0x438),
    (0xCA, 0x439),
    (0xCB, 0x43A),
    (0xCC, 0x43B),
    (0xCD, 0x43C),
    (0xCE, 0x43D),
    (0xCF, 0x43E),
    (0xD0, 0x43F),
    (0xD1, 0x44F),
    (0xD2, 0x440),
    (0xD3, 0x441),
    (0xD4, 0x442),
    (0xD5, 0x443),
    (0xD6, 0x436),
    (0xD7, 0x432),
    (0xD8, 0x44C),
    (0xD9, 0x44B),
    (0xDA, 0x437),
    (0xDB, 0x448),
    (0xDC, 0x44D),
    (0xDD, 0x449),
    (0xDE, 0x447),
    (0xDF, 0x44A),
    (0xE0, 0x42E),
    (0xE1, 0x410),
    (0xE2, 0x411),
    (0xE3, 0x426),
    (0xE4, 0x414),
    (0xE5, 0x415),
    (0xE6, 0x424),
    (0xE7, 0x413),
    (0xE8, 0x425),
    (0xE9, 0x418),
    (0xEA, 0x419),
    (0xEB, 0x41A),
    (0xEC, 0x41B),
    (0xED, 0x41C),
    (0xEE, 0x41D),
    (0xEF, 0x41E),
    (0xF0, 0x41F),
    (0xF1, 0x42F),
    (0xF2, 0x420),
    (0xF3, 0x421),
    (0xF4, 0x422),
    (0xF5, 0x423),
    (0xF6, 0x416),
    (0xF7, 0x412),
    (0xF8, 0x42C),
    (0xF9, 0x42B),
    (0xFA, 0x417),
    (0xFB, 0x428),
    (0xFC, 0x42D),
    (0xFD, 0x429),
    (0xFE, 0x427),
    (0xFF, 0x42A),
];
pub static MAC_ROMAN_CODEPOINTS: &[(u8, u32)] = &[
    (0x80, 0xC4),
    (0x81, 0xC5),
    (0x82, 0xC7),
    (0x83, 0xC9),
    (0x84, 0xD1),
    (0x85, 0xD6),
    (0x86, 0xDC),
    (0x87, 0xE1),
    (0x88, 0xE0),
    (0x89, 0xE2),
    (0x8A, 0xE4),
    (0x8B, 0xE3),
    (0x8C, 0xE5),
    (0x8D, 0xE7),
    (0x8E, 0xE9),
    (0x8F, 0xE8),
    (0x90, 0xEA),
    (0x91, 0xEB),
    (0x92, 0xED),
    (0x93, 0xEC),
    (0x94, 0xEE),
    (0x95, 0xEF),
    (0x96, 0xF1),
    (0x97, 0xF3),
    (0x98, 0xF2),
    (0x99, 0xF4),
    (0x9A, 0xF6),
    (0x9B, 0xF5),
    (0x9C, 0xFA),
    (0x9D, 0xF9),
    (0x9E, 0xFB),
    (0x9F, 0xFC),
    (0xA0, 0x2020),
    (0xA1, 0xB0),
    (0xA2, 0xA2),
    (0xA3, 0xA3),
    (0xA4, 0xA7),
    (0xA5, 0x2022),
    (0xA6, 0xB6),
    (0xA7, 0xDF),
    (0xA8, 0xAE),
    (0xA9, 0xA9),
    (0xAA, 0x2122),
    (0xAB, 0xB4),
    (0xAC, 0xA8),
    (0xAD, 0x2260),
    (0xAE, 0xC6),
    (0xAF, 0xD8),
    (0xB0, 0x221E),
    (0xB1, 0xB1),
    (0xB2, 0x2264),
    (0xB3, 0x2265),
    (0xB4, 0xA5),
    (0xB5, 0xB5),
    (0xB6, 0x2202),
    (0xB7, 0x2211),
    (0xB8, 0x220F),
    (0xB9, 0x3C0),
    (0xBA, 0x222B),
    (0xBB, 0xAA),
    (0xBC, 0xBA),
    (0xBD, 0x3A9),
    (0xBE, 0xE6),
    (0xBF, 0xF8),
    (0xC0, 0xBF),
    (0xC1, 0xA1),
    (0xC2, 0xAC),
    (0xC3, 0x221A),
    (0xC4, 0x192),
    (0xC5, 0x2248),
    (0xC6, 0x2206),
    (0xC7, 0xAB),
    (0xC8, 0xBB),
    (0xC9, 0x2026),
    (0xCA, 0xA0),
    (0xCB, 0xC0),
    (0xCC, 0xC3),
    (0xCD, 0xD5),
    (0xCE, 0x152),
    (0xCF, 0x153),
    (0xD0, 0x2013),
    (0xD1, 0x2014),
    (0xD2, 0x201C),
    (0xD3, 0x201D),
    (0xD4, 0x2018),
    (0xD5, 0x2019),
    (0xD6, 0xF7),
    (0xD7, 0x25CA),
    (0xD8, 0xFF),
    (0xD9, 0x178),
    (0xDA, 0x2044),
    (0xDB, 0x20AC),
    (0xDC, 0x2039),
    (0xDD, 0x203A),
    (0xDE, 0xFB01),
    (0xDF, 0xFB02),
    (0xE0, 0x2021),
    (0xE1, 0xB7),
    (0xE2, 0x201A),
    (0xE3, 0x201E),
    (0xE4, 0x2030),
    (0xE5, 0xC2),
    (0xE6, 0xCA),
    (0xE7, 0xC1),
    (0xE8, 0xCB),
    (0xE9, 0xC8),
    (0xEA, 0xCD),
    (0xEB, 0xCE),
    (0xEC, 0xCF),
    (0xED, 0xCC),
    (0xEE, 0xD3),
    (0xEF, 0xD4),
    (0xF0, 0xF8FF),
    (0xF1, 0xD2),
    (0xF2, 0xDA),
    (0xF3, 0xDB),
    (0xF4, 0xD9),
    (0xF5, 0x131),
    (0xF6, 0x2C6),
    (0xF7, 0x2DC),
    (0xF8, 0xAF),
    (0xF9, 0x2D8),
    (0xFA, 0x2D9),
    (0xFB, 0x2DA),
    (0xFC, 0xB8),
    (0xFD, 0x2DD),
    (0xFE, 0x2DB),
    (0xFF, 0x2C7),
];
