/* Generated by tools/generate-json-metadata.pl from php-src ext/json. */
/* Source revision: 8c63ec400ce8e07c57a8d9499317b96a8beafb8b */
/* Source files: ext/json/php_json.h, ext/json/json_arginfo.h, ext/json/json.c */

#define PTN_JSON_HEX_TAG 1
#define PTN_JSON_HEX_AMP 2
#define PTN_JSON_HEX_APOS 4
#define PTN_JSON_HEX_QUOT 8
#define PTN_JSON_FORCE_OBJECT 16
#define PTN_JSON_NUMERIC_CHECK 32
#define PTN_JSON_UNESCAPED_SLASHES 64
#define PTN_JSON_PRETTY_PRINT 128
#define PTN_JSON_UNESCAPED_UNICODE 256
#define PTN_JSON_PARTIAL_OUTPUT_ON_ERROR 512
#define PTN_JSON_PRESERVE_ZERO_FRACTION 1024
#define PTN_JSON_UNESCAPED_LINE_TERMINATORS 2048
#define PTN_JSON_OBJECT_AS_ARRAY 1
#define PTN_JSON_BIGINT_AS_STRING 2
#define PTN_JSON_INVALID_UTF8_IGNORE 1048576
#define PTN_JSON_INVALID_UTF8_SUBSTITUTE 2097152
#define PTN_JSON_THROW_ON_ERROR 4194304
#define PTN_JSON_ERROR_NONE 0
#define PTN_JSON_ERROR_DEPTH 1
#define PTN_JSON_ERROR_STATE_MISMATCH 2
#define PTN_JSON_ERROR_CTRL_CHAR 3
#define PTN_JSON_ERROR_SYNTAX 4
#define PTN_JSON_ERROR_UTF8 5
#define PTN_JSON_ERROR_RECURSION 6
#define PTN_JSON_ERROR_INF_OR_NAN 7
#define PTN_JSON_ERROR_UNSUPPORTED_TYPE 8
#define PTN_JSON_ERROR_INVALID_PROPERTY_NAME 9
#define PTN_JSON_ERROR_UTF16 10
#define PTN_JSON_ERROR_NON_BACKED_ENUM 11

#define PTN_JSON_ENCODE_ALLOWED_FLAGS (PTN_JSON_HEX_TAG | PTN_JSON_HEX_AMP | PTN_JSON_HEX_APOS | PTN_JSON_HEX_QUOT | PTN_JSON_FORCE_OBJECT | PTN_JSON_NUMERIC_CHECK | PTN_JSON_UNESCAPED_SLASHES | PTN_JSON_PRETTY_PRINT | PTN_JSON_UNESCAPED_UNICODE | PTN_JSON_PARTIAL_OUTPUT_ON_ERROR | PTN_JSON_PRESERVE_ZERO_FRACTION | PTN_JSON_UNESCAPED_LINE_TERMINATORS | PTN_JSON_INVALID_UTF8_IGNORE | PTN_JSON_INVALID_UTF8_SUBSTITUTE | PTN_JSON_THROW_ON_ERROR)
#define PTN_JSON_DECODE_ALLOWED_FLAGS (PTN_JSON_OBJECT_AS_ARRAY | PTN_JSON_BIGINT_AS_STRING | PTN_JSON_INVALID_UTF8_IGNORE | PTN_JSON_INVALID_UTF8_SUBSTITUTE | PTN_JSON_THROW_ON_ERROR)
#define PTN_JSON_VALIDATE_ALLOWED_FLAGS (PTN_JSON_INVALID_UTF8_IGNORE)
#define PTN_JSON_VALIDATE_ALLOWED_FLAGS_TEXT "JSON_INVALID_UTF8_IGNORE"
#define PTN_JSON_ERROR_LOCATION_FORMAT "%s near location %zu:%zu"
#define PTN_JSON_UNKNOWN_ERROR_MESSAGE "Unknown error"

typedef struct {
    const char *name;
    int64_t value;
    int is_error;
    int encode_flag;
    int decode_flag;
    int validate_flag;
    const char *message;
} PtnJsonConstantMetadata;

static const PtnJsonConstantMetadata ptn_json_constant_metadata_entries[] = {
    { "JSON_HEX_TAG", PTN_JSON_HEX_TAG, 0, 1, 0, 0, NULL },
    { "JSON_HEX_AMP", PTN_JSON_HEX_AMP, 0, 1, 0, 0, NULL },
    { "JSON_HEX_APOS", PTN_JSON_HEX_APOS, 0, 1, 0, 0, NULL },
    { "JSON_HEX_QUOT", PTN_JSON_HEX_QUOT, 0, 1, 0, 0, NULL },
    { "JSON_FORCE_OBJECT", PTN_JSON_FORCE_OBJECT, 0, 1, 0, 0, NULL },
    { "JSON_NUMERIC_CHECK", PTN_JSON_NUMERIC_CHECK, 0, 1, 0, 0, NULL },
    { "JSON_UNESCAPED_SLASHES", PTN_JSON_UNESCAPED_SLASHES, 0, 1, 0, 0, NULL },
    { "JSON_PRETTY_PRINT", PTN_JSON_PRETTY_PRINT, 0, 1, 0, 0, NULL },
    { "JSON_UNESCAPED_UNICODE", PTN_JSON_UNESCAPED_UNICODE, 0, 1, 0, 0, NULL },
    { "JSON_PARTIAL_OUTPUT_ON_ERROR", PTN_JSON_PARTIAL_OUTPUT_ON_ERROR, 0, 1, 0, 0, NULL },
    { "JSON_PRESERVE_ZERO_FRACTION", PTN_JSON_PRESERVE_ZERO_FRACTION, 0, 1, 0, 0, NULL },
    { "JSON_UNESCAPED_LINE_TERMINATORS", PTN_JSON_UNESCAPED_LINE_TERMINATORS, 0, 1, 0, 0, NULL },
    { "JSON_OBJECT_AS_ARRAY", PTN_JSON_OBJECT_AS_ARRAY, 0, 0, 1, 0, NULL },
    { "JSON_BIGINT_AS_STRING", PTN_JSON_BIGINT_AS_STRING, 0, 0, 1, 0, NULL },
    { "JSON_INVALID_UTF8_IGNORE", PTN_JSON_INVALID_UTF8_IGNORE, 0, 1, 1, 1, NULL },
    { "JSON_INVALID_UTF8_SUBSTITUTE", PTN_JSON_INVALID_UTF8_SUBSTITUTE, 0, 1, 1, 0, NULL },
    { "JSON_THROW_ON_ERROR", PTN_JSON_THROW_ON_ERROR, 0, 1, 1, 0, NULL },
    { "JSON_ERROR_NONE", PTN_JSON_ERROR_NONE, 1, 0, 0, 0, "No error" },
    { "JSON_ERROR_DEPTH", PTN_JSON_ERROR_DEPTH, 1, 0, 0, 0, "Maximum stack depth exceeded" },
    { "JSON_ERROR_STATE_MISMATCH", PTN_JSON_ERROR_STATE_MISMATCH, 1, 0, 0, 0, "State mismatch (invalid or malformed JSON)" },
    { "JSON_ERROR_CTRL_CHAR", PTN_JSON_ERROR_CTRL_CHAR, 1, 0, 0, 0, "Control character error, possibly incorrectly encoded" },
    { "JSON_ERROR_SYNTAX", PTN_JSON_ERROR_SYNTAX, 1, 0, 0, 0, "Syntax error" },
    { "JSON_ERROR_UTF8", PTN_JSON_ERROR_UTF8, 1, 0, 0, 0, "Malformed UTF-8 characters, possibly incorrectly encoded" },
    { "JSON_ERROR_RECURSION", PTN_JSON_ERROR_RECURSION, 1, 0, 0, 0, "Recursion detected" },
    { "JSON_ERROR_INF_OR_NAN", PTN_JSON_ERROR_INF_OR_NAN, 1, 0, 0, 0, "Inf and NaN cannot be JSON encoded" },
    { "JSON_ERROR_UNSUPPORTED_TYPE", PTN_JSON_ERROR_UNSUPPORTED_TYPE, 1, 0, 0, 0, "Type is not supported" },
    { "JSON_ERROR_INVALID_PROPERTY_NAME", PTN_JSON_ERROR_INVALID_PROPERTY_NAME, 1, 0, 0, 0, "The decoded property name is invalid" },
    { "JSON_ERROR_UTF16", PTN_JSON_ERROR_UTF16, 1, 0, 0, 0, "Single unpaired UTF-16 surrogate in unicode escape" },
    { "JSON_ERROR_NON_BACKED_ENUM", PTN_JSON_ERROR_NON_BACKED_ENUM, 1, 0, 0, 0, "Non-backed enums have no default serialization" },
};

static const size_t ptn_json_constant_metadata_len =
    sizeof(ptn_json_constant_metadata_entries) / sizeof(ptn_json_constant_metadata_entries[0]);

static PTN_UNUSED const PtnJsonConstantMetadata *ptn_json_constant_metadata_by_name(const char *name) {
    for (size_t i = 0; i < ptn_json_constant_metadata_len; i++) {
        if (strcmp(name, ptn_json_constant_metadata_entries[i].name) == 0) {
            return &ptn_json_constant_metadata_entries[i];
        }
    }
    return NULL;
}

static PTN_UNUSED const PtnJsonConstantMetadata *ptn_json_error_metadata_by_code(int error) {
    for (size_t i = 0; i < ptn_json_constant_metadata_len; i++) {
        const PtnJsonConstantMetadata *metadata = &ptn_json_constant_metadata_entries[i];
        if (metadata->is_error && metadata->value == error) {
            return metadata;
        }
    }
    return NULL;
}

static PTN_UNUSED int ptn_json_constant_value(const char *name, int64_t *value_out) {
    const PtnJsonConstantMetadata *metadata = ptn_json_constant_metadata_by_name(name);
    if (metadata == NULL) {
        return 0;
    }
    *value_out = metadata->value;
    return 1;
}

static PTN_UNUSED void ptn_defined_constants_add_json(PtnValue table) {
    for (size_t i = 0; i < ptn_json_constant_metadata_len; i++) {
        const PtnJsonConstantMetadata *metadata = &ptn_json_constant_metadata_entries[i];
        ptn_array_set_entry(table.as.array, ptn_array_string_key(metadata->name), ptn_int(metadata->value));
    }
}

static PTN_UNUSED int ptn_reflection_constant_is_json(const char *name) {
    return ptn_json_constant_metadata_by_name(name) != NULL;
}

static PTN_UNUSED const char *ptn_json_error_message(int error) {
    const PtnJsonConstantMetadata *metadata = ptn_json_error_metadata_by_code(error);
    return metadata == NULL ? PTN_JSON_UNKNOWN_ERROR_MESSAGE : metadata->message;
}
