#!/usr/bin/env python3
"""Generate PTN's bounded HTML charset tables from php-src.

Canonical PHP sources:
  ext/standard/html_tables.h
  ext/standard/html_tables/html_table_gen.php
  ext/standard/html_tables/mappings/*.TXT

The generated runtime chunk is checked in so normal PTN builds do not depend on
a php-src checkout.
"""

from __future__ import annotations

import argparse
import os
import re
from pathlib import Path


CS_TO_PTN_ENCODING = {
    "cs_utf_8": "PTN_HTML_ENCODING_UTF8",
    "cs_8859_1": "PTN_HTML_ENCODING_ISO_8859_1",
    "cs_cp1252": "PTN_HTML_ENCODING_WINDOWS_1252",
    "cs_8859_15": "PTN_HTML_ENCODING_ISO_8859_15",
    "cs_cp1251": "PTN_HTML_ENCODING_WINDOWS_1251",
    "cs_8859_5": "PTN_HTML_ENCODING_ISO_8859_5",
    "cs_cp866": "PTN_HTML_ENCODING_CP866",
    "cs_macroman": "PTN_HTML_ENCODING_MACROMAN",
    "cs_koi8r": "PTN_HTML_ENCODING_KOI8_R",
    "cs_big5": "PTN_HTML_ENCODING_LEGACY_MULTIBYTE",
    "cs_gb2312": "PTN_HTML_ENCODING_LEGACY_MULTIBYTE",
    "cs_big5hkscs": "PTN_HTML_ENCODING_LEGACY_MULTIBYTE",
    "cs_sjis": "PTN_HTML_ENCODING_SJIS",
    "cs_eucjp": "PTN_HTML_ENCODING_EUC_JP",
}

SINGLE_BYTE_TABLES = [
    ("ISO_8859_1", "PTN_HTML_ENCODING_ISO_8859_1", "8859-1.TXT"),
    ("WINDOWS_1252", "PTN_HTML_ENCODING_WINDOWS_1252", "CP1252.TXT"),
    ("ISO_8859_15", "PTN_HTML_ENCODING_ISO_8859_15", "8859-15.TXT"),
    ("WINDOWS_1251", "PTN_HTML_ENCODING_WINDOWS_1251", "CP1251.TXT"),
    ("ISO_8859_5", "PTN_HTML_ENCODING_ISO_8859_5", "8859-5.TXT"),
    ("CP866", "PTN_HTML_ENCODING_CP866", "CP866.TXT"),
    ("MACROMAN", "PTN_HTML_ENCODING_MACROMAN", "ROMAN.TXT"),
    ("KOI8_R", "PTN_HTML_ENCODING_KOI8_R", "KOI8-R.TXT"),
]


def php_src_default() -> Path:
    env = os.environ.get("PHP_SRC_PHPT")
    if env:
        return Path(env)
    for candidate in (Path("/home/claude/php-src-phpt"), Path(".runtime/php-src-phpt")):
        if candidate.exists():
            return candidate
    return Path("/home/claude/php-src-phpt")


def c_escape(text: str) -> str:
    return text.replace("\\", "\\\\").replace('"', '\\"')


def parse_charset_map(html_tables_h: Path) -> list[tuple[str, str]]:
    source = html_tables_h.read_text()
    match = re.search(r"charset_map\[\]\s*=\s*\{(.*?)\};", source, re.S)
    if not match:
        raise SystemExit(f"could not find charset_map[] in {html_tables_h}")
    result: list[tuple[str, str]] = []
    for label, cs_name in re.findall(r'\{\s*"([^"]+)".*?(cs_[a-z0-9_]+)\s*\}', match.group(1)):
        encoding = CS_TO_PTN_ENCODING.get(cs_name)
        if encoding is None:
            raise SystemExit(f"unmapped PHP charset enum {cs_name} for {label}")
        result.append((label, encoding))
    return result


def parse_mapping(path: Path) -> list[int]:
    table = [0xFFFF] * 256
    pattern = re.compile(r"^0x([0-9a-fA-F]{2})\s+0x([0-9a-fA-F]{2,6})\b")
    for line in path.read_text(errors="replace").splitlines():
        match = pattern.match(line)
        if not match:
            continue
        byte = int(match.group(1), 16)
        codepoint = int(match.group(2), 16)
        table[byte] = codepoint
    return table[0x80:]


def format_table(values: list[int]) -> str:
    lines = []
    for offset in range(0, len(values), 8):
        chunk = values[offset : offset + 8]
        lines.append("    " + ", ".join(f"0x{value:04X}" for value in chunk) + ",")
    return "\n".join(lines)


def generate(php_src: Path) -> str:
    html_tables_h = php_src / "ext/standard/html_tables.h"
    mappings_dir = php_src / "ext/standard/html_tables/mappings"
    if not html_tables_h.exists():
        raise SystemExit(f"missing PHP html tables source: {html_tables_h}")
    if not mappings_dir.exists():
        raise SystemExit(f"missing PHP charset mapping directory: {mappings_dir}")

    charset_map = parse_charset_map(html_tables_h)
    tables = [
        (ident, runtime_enum, parse_mapping(mappings_dir / mapping_file))
        for ident, runtime_enum, mapping_file in SINGLE_BYTE_TABLES
    ]

    out: list[str] = []
    out.append("/*")
    out.append(" * Generated by tools/generate-html-tables.py.")
    out.append(" * Source: php-src ext/standard/html_tables.h and html_tables/mappings.")
    out.append(" * PHP source license: BSD-3-Clause, The PHP Group and Contributors.")
    out.append(" */")
    out.append("")
    out.append("typedef struct {")
    out.append("    const char *label;")
    out.append("    PtnHtmlEncoding encoding;")
    out.append("} PtnHtmlCharsetMapEntry;")
    out.append("")
    out.append("static const PtnHtmlCharsetMapEntry PTN_HTML_GENERATED_CHARSET_MAP[] = {")
    for label, encoding in charset_map:
        out.append(f'    {{ "{c_escape(label)}", {encoding} }},')
    out.append("};")
    out.append("")
    out.append("static const PtnHtmlCharsetMapEntry *ptn_html_generated_charset_map(size_t *count) {")
    out.append("    *count = sizeof(PTN_HTML_GENERATED_CHARSET_MAP) / sizeof(PTN_HTML_GENERATED_CHARSET_MAP[0]);")
    out.append("    return PTN_HTML_GENERATED_CHARSET_MAP;")
    out.append("}")
    out.append("")
    for ident, _runtime_enum, values in tables:
        out.append(f"static const unsigned int PTN_HTML_GENERATED_{ident}_TABLE[128] = {{")
        out.append(format_table(values))
        out.append("};")
        out.append("")
    out.append("static const unsigned int *ptn_html_generated_single_byte_table(PtnHtmlEncoding encoding) {")
    out.append("    switch (encoding) {")
    for ident, runtime_enum, _values in tables:
        out.append(f"        case {runtime_enum}: return PTN_HTML_GENERATED_{ident}_TABLE;")
    out.append("        default: return NULL;")
    out.append("    }")
    out.append("}")
    out.append("")
    return "\n".join(out)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--php-src", type=Path, default=php_src_default())
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("src/backend/runtime/html_tables_generated.c"),
    )
    args = parser.parse_args()
    args.output.write_text(generate(args.php_src))


if __name__ == "__main__":
    main()
