#!/usr/bin/env bash
set -euo pipefail

repo_root=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
php_src=${PHP_SRC_PHPT:-/home/claude/php-src-phpt}

if [[ ! -d "$php_src/.git" ]]; then
    echo "php-src checkout not found at $php_src" >&2
    echo "Set PHP_SRC_PHPT to a php-src checkout." >&2
    exit 1
fi

arginfo="$php_src/ext/standard/basic_functions_arginfo.h"
main_c="$php_src/main/main.c"
formatted_print_c="$php_src/ext/standard/formatted_print.c"

for source in "$arginfo" "$main_c" "$formatted_print_c"; do
    if [[ ! -f "$source" ]]; then
        echo "required php-src file not found: $source" >&2
        exit 1
    fi
done

revision=$(git -C "$php_src" rev-parse HEAD)
precision_default=$(sed -nE 's/.*PHP_INI_ENTRY\("precision",[[:space:]]*"([^"]+)".*/\1/p' "$main_c" | head -n1)
serialize_precision_default=$(sed -nE 's/.*STD_PHP_INI_ENTRY\("serialize_precision",[[:space:]]*"([^"]+)".*/\1/p' "$main_c" | head -n1)
sprintf_default_float_precision=$(sed -nE 's/^#define[[:space:]]+FLOAT_PRECISION[[:space:]]+([0-9]+).*/\1/p' "$formatted_print_c" | head -n1)
sprintf_max_float_precision=$(sed -nE 's/^#define[[:space:]]+MAX_FLOAT_PRECISION[[:space:]]+([0-9]+).*/\1/p' "$formatted_print_c" | head -n1)
sprintf_num_buffer_size=$(sed -nE 's/^#define[[:space:]]+NUM_BUF_SIZE[[:space:]]+([0-9]+).*/\1/p' "$formatted_print_c" | head -n1)

if [[ -z "$precision_default" || -z "$serialize_precision_default" ||
      -z "$sprintf_default_float_precision" || -z "$sprintf_max_float_precision" ||
      -z "$sprintf_num_buffer_size" ]]; then
    echo "failed to extract scalar-format defaults from php-src" >&2
    exit 1
fi

is_locale_or_nl_langinfo_constant() {
    case "$1" in
        LC_*|ABDAY_*|DAY_*|ABMON_*|MON_*|AM_STR|PM_STR|D_T_FMT|D_FMT|T_FMT|T_FMT_AMPM|ERA|ERA_YEAR|ERA_D_T_FMT|ERA_D_FMT|ERA_T_FMT|ALT_DIGITS|INT_CURR_SYMBOL|CURRENCY_SYMBOL|CRNCYSTR|MON_DECIMAL_POINT|MON_THOUSANDS_SEP|MON_GROUPING|POSITIVE_SIGN|NEGATIVE_SIGN|INT_FRAC_DIGITS|FRAC_DIGITS|P_CS_PRECEDES|P_SEP_BY_SPACE|N_CS_PRECEDES|N_SEP_BY_SPACE|P_SIGN_POSN|N_SIGN_POSN|DECIMAL_POINT|RADIXCHAR|THOUSANDS_SEP|THOUSEP|GROUPING|YESEXPR|NOEXPR|YESSTR|NOSTR|CODESET)
            return 0
            ;;
        *)
            return 1
            ;;
    esac
}

declare -a all_names=()
declare -a all_cvalues=()
while IFS=$'\t' read -r name cvalue; do
    if is_locale_or_nl_langinfo_constant "$name"; then
        all_names+=("$name")
        all_cvalues+=("$cvalue")
    fi
done < <(sed -nE 's/.*REGISTER_LONG_CONSTANT\("([A-Z0-9_]+)",[[:space:]]*([A-Z0-9_]+),.*/\1\t\2/p' "$arginfo")

if [[ ${#all_names[@]} -eq 0 ]]; then
    echo "failed to extract locale/nl_langinfo constants from php-src" >&2
    exit 1
fi

tmpdir=$(mktemp -d)
trap 'rm -rf "$tmpdir"' EXIT

probe_c="$tmpdir/probe.c"
probe_bin="$tmpdir/probe"
probe_out="$tmpdir/probe.out"

{
    printf '#define _GNU_SOURCE\n'
    printf '#include <stdio.h>\n'
    printf '#include <locale.h>\n'
    printf '#include <langinfo.h>\n'
    printf 'int main(void) {\n'
    for i in "${!all_names[@]}"; do
        name=${all_names[$i]}
        cvalue=${all_cvalues[$i]}
        printf '#ifdef %s\n' "$cvalue"
        printf '    printf("%s=%%lld\\n", (long long)%s);\n' "$name" "$cvalue"
        printf '#endif\n'
    done
    printf '    return 0;\n'
    printf '}\n'
} > "$probe_c"

cc -std=c99 -Wall -Wextra -o "$probe_bin" "$probe_c"
"$probe_bin" > "$probe_out"

declare -A value_by_name=()
while IFS='=' read -r name value; do
    value_by_name[$name]=$value
done < "$probe_out"

declare -a locale_names=()
declare -a nl_names=()
for name in "${all_names[@]}"; do
    if [[ -z "${value_by_name[$name]+set}" ]]; then
        continue
    fi
    case "$name" in
        LC_*) locale_names+=("$name") ;;
        *) nl_names+=("$name") ;;
    esac
done

if [[ ${#locale_names[@]} -eq 0 || ${#nl_names[@]} -eq 0 ]]; then
    echo "host C library did not expose required locale/nl_langinfo constants" >&2
    exit 1
fi

emit_c_x_macro() {
    local macro_name=$1
    shift
    local -a names=("$@")
    printf '#define %s(X)' "$macro_name"
    if [[ ${#names[@]} -eq 0 ]]; then
        printf '\n'
        return
    fi
    printf ' \\\n'
    for i in "${!names[@]}"; do
        local name=${names[$i]}
        local suffix=' \'
        if [[ $i -eq $((${#names[@]} - 1)) ]]; then
            suffix=''
        fi
        printf '    X("%s", PTN_%s)%s\n' "$name" "$name" "$suffix"
    done
}

emit_rust_names() {
    shift
    local -a names=("$@")
    for name in "${names[@]}"; do
        printf '    "%s",\n' "$name"
    done
}

c_output="$repo_root/src/backend/runtime/php_src_metadata.c"
rust_output="$repo_root/src/php_src_metadata.rs"

{
    printf '/* @generated by tools/generate-php-src-metadata.sh from php-src@%s. */\n' "$revision"
    printf '/* Do not edit by hand. */\n\n'
    printf '#define PTN_PHP_SRC_METADATA_REVISION "%s"\n' "$revision"
    for name in "${locale_names[@]}" "${nl_names[@]}"; do
        printf '#define PTN_%s %s\n' "$name" "${value_by_name[$name]}"
    done
    printf '#define PTN_DEFAULT_PRECISION %s\n' "$precision_default"
    printf '#define PTN_DEFAULT_SERIALIZE_PRECISION %s\n' "$serialize_precision_default"
    printf '#define PTN_SPRINTF_DEFAULT_FLOAT_PRECISION %s\n' "$sprintf_default_float_precision"
    printf '#define PTN_SPRINTF_MAX_FLOAT_PRECISION %s\n' "$sprintf_max_float_precision"
    printf '#define PTN_SPRINTF_NUM_BUFFER_SIZE %s\n\n' "$sprintf_num_buffer_size"
    emit_c_x_macro PTN_PHP_SRC_LOCALE_CONSTANTS "${locale_names[@]}"
    printf '\n'
    emit_c_x_macro PTN_PHP_SRC_NL_LANGINFO_CONSTANTS "${nl_names[@]}"
    printf '\n'
    printf '#define PTN_PHP_SRC_SCALAR_FORMAT_INI_ENTRIES(X) \\\n'
    printf '    X("precision", PTN_DEFAULT_PRECISION) \\\n'
    printf '    X("serialize_precision", PTN_DEFAULT_SERIALIZE_PRECISION)\n\n'
    printf '#define PTN_PHP_SRC_LOCALE_CATEGORY_MAPPINGS(X) \\\n'
    printf '    X(PTN_LC_CTYPE, LC_CTYPE) \\\n'
    printf '    X(PTN_LC_NUMERIC, LC_NUMERIC) \\\n'
    printf '    X(PTN_LC_TIME, LC_TIME) \\\n'
    printf '    X(PTN_LC_COLLATE, LC_COLLATE) \\\n'
    printf '    X(PTN_LC_MONETARY, LC_MONETARY) \\\n'
    printf '    X(PTN_LC_ALL, LC_ALL)\n\n'
    printf '#ifdef PTN_LC_MESSAGES\n'
    printf '#define PTN_PHP_SRC_LOCALE_MESSAGES_CATEGORY_MAPPING(X) X(PTN_LC_MESSAGES, LC_MESSAGES)\n'
    printf '#else\n'
    printf '#define PTN_PHP_SRC_LOCALE_MESSAGES_CATEGORY_MAPPING(X)\n'
    printf '#endif\n'
} > "$c_output"

{
    printf '// @generated by tools/generate-php-src-metadata.sh from php-src@%s.\n' "$revision"
    printf '// Do not edit by hand.\n\n'
    printf 'pub const PHP_SRC_METADATA_REVISION: &str = "%s";\n' "$revision"
    printf 'pub const SPRINTF_DEFAULT_FLOAT_PRECISION: i32 = %s;\n' "$sprintf_default_float_precision"
    printf 'pub const SPRINTF_MAX_FLOAT_PRECISION: i32 = %s;\n' "$sprintf_max_float_precision"
    printf 'pub const SPRINTF_NUM_BUFFER_SIZE: usize = %s;\n\n' "$sprintf_num_buffer_size"
    printf 'pub const SCALAR_FORMAT_INI_DEFAULTS: &[(&str, &str)] = &[\n'
    printf '    ("precision", "%s"),\n' "$precision_default"
    printf '    ("serialize_precision", "%s"),\n' "$serialize_precision_default"
    printf '];\n\n'
    printf 'pub const LOCALE_CONSTANT_NAMES: &[&str] = &[\n'
    emit_rust_names locale "${locale_names[@]}"
    printf '];\n\n'
    printf 'pub const NL_LANGINFO_CONSTANT_NAMES: &[&str] = &[\n'
    emit_rust_names nl "${nl_names[@]}"
    printf '];\n\n'
    printf 'pub fn is_locale_or_nl_langinfo_constant_name(name: &str) -> bool {\n'
    printf '    LOCALE_CONSTANT_NAMES\n'
    printf '        .iter()\n'
    printf '        .chain(NL_LANGINFO_CONSTANT_NAMES.iter())\n'
    printf '        .any(|candidate| *candidate == name)\n'
    printf '}\n\n'
    printf 'pub fn scalar_format_ini_canonical_name(name: &str) -> Option<&'"'"'static str> {\n'
    printf '    SCALAR_FORMAT_INI_DEFAULTS\n'
    printf '        .iter()\n'
    printf '        .find_map(|(candidate, _)| candidate.eq_ignore_ascii_case(name).then_some(*candidate))\n'
    printf '}\n\n'
    printf 'pub fn scalar_format_ini_default(name: &str) -> Option<&'"'"'static str> {\n'
    printf '    SCALAR_FORMAT_INI_DEFAULTS\n'
    printf '        .iter()\n'
    printf '        .find_map(|(candidate, default)| candidate.eq_ignore_ascii_case(name).then_some(*default))\n'
    printf '}\n'
} > "$rust_output"

echo "generated $c_output and $rust_output from php-src@$revision"
