#!/usr/bin/env python3
"""Write a PHPT manifest for rows not reported by shard checkpoints."""

from __future__ import annotations

import argparse
import csv
import re
from pathlib import Path


SHARD_RE = re.compile(r"shard-(\d+)\.txt$")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("artifact_roots", nargs="+", type=Path)
    parser.add_argument("--out", type=Path, required=True)
    parser.add_argument("--expected-shards", type=int, default=None)
    return parser.parse_args()


def trim_manifest_row(line: str) -> str:
    return line.split("#", 1)[0].strip()


def load_manifest(path: Path) -> list[str]:
    rows: list[str] = []
    for raw in path.read_text(encoding="utf-8").splitlines():
        value = trim_manifest_row(raw)
        if value:
            rows.append(value)
    return rows


def shard_index(path: Path) -> int:
    match = SHARD_RE.search(path.name)
    if match is None:
        raise ValueError(f"could not determine shard index from {path}")
    return int(match.group(1))


def artifact_dir_for_manifest(path: Path) -> Path:
    # .../phpt-full-corpus-shard-N/full-phpt-shards/shard-N.txt
    return path.parents[1]


def latest_row_results(artifact_dir: Path, index: int) -> Path | None:
    result_dir = artifact_dir / "full-phpt-results" / f"shard-{index}"
    candidates = sorted(result_dir.glob("row-results-*-live.tsv"))
    if candidates:
        return candidates[-1]
    candidates = sorted(result_dir.glob("row-results-*.tsv"))
    if candidates:
        return candidates[-1]
    return None


def covered_indexes(path: Path, row_count: int) -> set[int]:
    covered: set[int] = set()
    with path.open(newline="", encoding="utf-8") as handle:
        reader = csv.DictReader(handle, delimiter="\t")
        for record in reader:
            try:
                start = int(record["index"])
                count = int(record["rows"])
            except (KeyError, TypeError, ValueError):
                continue
            if start < 0 or count <= 0:
                continue
            for index in range(start, min(start + count, row_count)):
                covered.add(index)
    return covered


def find_shard_manifests(roots: list[Path]) -> list[Path]:
    manifests: list[Path] = []
    for root in roots:
        manifests.extend(root.glob("phpt-full-corpus-shard-*/full-phpt-shards/shard-*.txt"))
        manifests.extend(root.glob("full-phpt-shards/shard-*.txt"))
    return sorted(set(manifests), key=lambda path: (shard_index(path), path.as_posix()))


def main() -> int:
    args = parse_args()
    manifests = find_shard_manifests(args.artifact_roots)
    if not manifests:
        raise SystemExit("no shard manifests found in artifact roots")

    found_shards = {shard_index(path) for path in manifests}
    if args.expected_shards is not None:
        expected = set(range(args.expected_shards))
        missing = sorted(expected - found_shards)
        if missing:
            raise SystemExit(
                "missing shard manifests: " + ", ".join(str(item) for item in missing)
            )

    remaining: list[str] = []
    total_rows = 0
    reported_rows = 0
    for manifest in manifests:
        index = shard_index(manifest)
        rows = load_manifest(manifest)
        total_rows += len(rows)
        row_results = latest_row_results(artifact_dir_for_manifest(manifest), index)
        covered: set[int] = set()
        if row_results is not None:
            covered = covered_indexes(row_results, len(rows))
        reported_rows += len(covered)
        remaining.extend(row for row_index, row in enumerate(rows) if row_index not in covered)

    args.out.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "# Generated by tools/phpt-continuation-manifest.py",
        f"# artifact-roots: {', '.join(str(root) for root in args.artifact_roots)}",
        f"# shard-manifests: {len(manifests)}",
        f"# total-input-rows: {total_rows}",
        f"# reported-rows: {reported_rows}",
        f"# remaining-rows: {len(remaining)}",
        "",
        *remaining,
    ]
    args.out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(
        "continuation-manifest: "
        f"shards={len(manifests)} total={total_rows} reported={reported_rows} "
        f"remaining={len(remaining)} out={args.out}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
