#!/usr/bin/env bash
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
source "$repo_root/tools/phpt-corpus.sh"

usage() {
  cat <<'EOF'
Usage: tools/phpt-full-corpus-shard.sh [--manifest FILE] --shard-index N --shard-count N --out FILE

Write one deterministic shard of the full php-src PHPT corpus or a manifest.

Rows are sorted lexicographically and assigned by zero-based row number modulo
the shard count. Shard indexes are zero-based.
EOF
}

manifest=
shard_index=
shard_count=
out=

while [[ $# -gt 0 ]]; do
  case "$1" in
    --shard-index)
      [[ $# -ge 2 ]] || { echo "--shard-index requires a value" >&2; exit 2; }
      shard_index=$2
      shift 2
      ;;
    --shard-count)
      [[ $# -ge 2 ]] || { echo "--shard-count requires a value" >&2; exit 2; }
      shard_count=$2
      shift 2
      ;;
    --out)
      [[ $# -ge 2 ]] || { echo "--out requires a value" >&2; exit 2; }
      out=$2
      shift 2
      ;;
    --manifest)
      [[ $# -ge 2 ]] || { echo "--manifest requires a value" >&2; exit 2; }
      manifest=$2
      shift 2
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "unknown argument: $1" >&2
      usage >&2
      exit 2
      ;;
  esac
done

if [[ ! "$shard_index" =~ ^[0-9]+$ ]]; then
  echo "--shard-index must be a non-negative integer: ${shard_index:-}" >&2
  exit 2
fi
if [[ ! "$shard_count" =~ ^[0-9]+$ || "$shard_count" -le 0 ]]; then
  echo "--shard-count must be a positive integer: ${shard_count:-}" >&2
  exit 2
fi
if [[ "$shard_index" -ge "$shard_count" ]]; then
  echo "--shard-index must be less than --shard-count: $shard_index >= $shard_count" >&2
  exit 2
fi
if [[ -z "$out" ]]; then
  echo "--out is required" >&2
  exit 2
fi

php_src="$(ptn_resolve_phpt_corpus "$repo_root")"
corpus_revision="$(ptn_phpt_corpus_revision "$php_src")"
mkdir -p "$(dirname "$out")"

tmp="$(mktemp "$repo_root/.runtime/phpt-shard.XXXXXX")"
trap 'rm -f "$tmp"' EXIT

if [[ -n "$manifest" ]]; then
  manifest_path="$manifest"
  if [[ "$manifest_path" != /* ]]; then
    manifest_path="$repo_root/$manifest_path"
  fi
  if [[ ! -f "$manifest_path" ]]; then
    echo "--manifest file not found: $manifest" >&2
    exit 2
  fi
  grep -Ev '^[[:space:]]*(#|$)' "$manifest_path" > "$tmp"
else
  (cd "$php_src" && find . -path './.git' -prune -o -type f -name '*.phpt' -print \
    | sed 's#^\./##' \
    | LC_ALL=C sort) > "$tmp"
fi

total_rows="$(wc -l < "$tmp" | tr -d '[:space:]')"

{
  echo "# Generated by tools/phpt-full-corpus-shard.sh"
  echo "# corpus: $php_src"
  echo "# corpus-revision: $corpus_revision"
  echo "# total-rows: $total_rows"
  if [[ -n "$manifest" ]]; then
    echo "# manifest: $manifest"
  fi
  echo "# shard-index: $shard_index"
  echo "# shard-count: $shard_count"
  echo
  awk -v shard_index="$shard_index" -v shard_count="$shard_count" '
    ((NR - 1) % shard_count) == shard_index { print }
  ' "$tmp"
} > "$out"

selected_rows="$(grep -Ev '^[[:space:]]*(#|$)' "$out" | wc -l | tr -d '[:space:]')"
printf 'phpt-shard: index=%s count=%s total=%s selected=%s path=%s\n' \
  "$shard_index" "$shard_count" "$total_rows" "$selected_rows" "$out"
