#!/usr/bin/env python3
"""Create deterministic manifests for concurrent continuation PHPT shards."""

from __future__ import annotations

import argparse
from pathlib import Path


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--run-dir", type=Path, required=True)
    parser.add_argument("--shards", type=int, default=4)
    return parser.parse_args()


def manifest_rows(path: Path) -> list[str]:
    rows: list[str] = []
    for raw in path.read_text(encoding="utf-8").splitlines():
        row = raw.split("#", 1)[0].strip()
        if row:
            rows.append(row)
    if not rows:
        raise SystemExit(f"manifest contains no PHPT rows: {path}")
    return rows


def existing_results(path: Path) -> tuple[set[str], dict[str, int]]:
    counts = {
        "reported": 0,
        "passed": 0,
        "failed": 0,
        "skipped": 0,
        "warned": 0,
        "crashed": 0,
    }
    if not path.is_file():
        return set(), counts

    reported: set[str] = set()
    for raw in path.read_text(encoding="utf-8").splitlines()[1:]:
        parts = raw.split("\t")
        if len(parts) != 14:
            continue
        row = parts[2]
        if row in reported:
            continue
        reported.add(row)
        counts["reported"] += 1
        counts["passed"] += int(parts[8])
        counts["failed"] += int(parts[9])
        counts["skipped"] += int(parts[10])
        counts["warned"] += int(parts[11])
        counts["crashed"] += int(parts[13])
    return reported, counts


def atomic_write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_name(f".{path.name}.tmp")
    temporary.write_text(content, encoding="utf-8")
    temporary.replace(path)


def main() -> int:
    args = parse_args()
    if args.shards < 1:
        raise SystemExit("--shards must be positive")

    run_dir = args.run_dir.resolve()
    manifest_path = run_dir / "manifest.txt"
    rows = manifest_rows(manifest_path)
    reported, counts = existing_results(run_dir / "row-results.tsv")
    missing = [row for row in rows if row not in reported]
    shard_rows = [[] for _ in range(args.shards)]
    for index, row in enumerate(rows):
        if row not in reported:
            shard_rows[index % args.shards].append(row)

    shards_dir = run_dir / "shards"
    plan_path = shards_dir / "plan.tsv"
    plan_lines = ["shard\tremaining\tmanifest"]
    for index, rows_for_shard in enumerate(shard_rows):
        shard_dir = shards_dir / f"shard-{index:02d}"
        shard_manifest = shard_dir / "manifest.txt"
        content = "\n".join(
            [
                "# Generated by tools/prepare-local-phpt-shards.py",
                f"# source run: {run_dir}",
                f"# shard: {index}/{args.shards}",
                "",
                *rows_for_shard,
            ]
        ) + "\n"
        if shard_manifest.exists() and shard_manifest.read_text(encoding="utf-8") != content:
            raise SystemExit(
                f"existing shard manifest differs: {shard_manifest}; use a new run directory"
            )
        atomic_write(shard_manifest, content)
        plan_lines.append(
            f"{index}\t{len(rows_for_shard)}\t{shard_manifest.relative_to(run_dir)}"
        )

    atomic_write(plan_path, "\n".join(plan_lines) + "\n")
    baseline_lines = [f"total\t{len(rows)}"]
    baseline_lines.extend(f"{name}\t{value}" for name, value in counts.items())
    atomic_write(shards_dir / "baseline.tsv", "\n".join(baseline_lines) + "\n")

    print(f"run_dir={run_dir}")
    print(f"total={len(rows)}")
    print(f"already_reported={counts['reported']}")
    print(f"remaining={len(missing)}")
    for index, rows_for_shard in enumerate(shard_rows):
        print(f"shard_{index:02d}={len(rows_for_shard)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
