#!/usr/bin/env bash
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
source "$repo_root/tools/phpt-corpus.sh"

usage() {
  cat <<'EOF'
Usage: tools/run-phpt-baseline.sh [--tier N|all] [--generate-only] [--classify-only] [--out-dir DIR]

Generate deterministic broad PHPT baseline manifests from the canonical
php-src corpus and, by default, run the 1,000-row tier through run-tests.php.
Use --classify-only to generate blocker maps without building phpc or running
the selected runnable rows.

Defaults:
  --tier 1000
  --out-dir .runtime/phpt-baseline

Environment:
  PHP_SRC_PHPT          php-src checkout with run-tests.php
  PHPT_BASELINE_DIR    output directory for generated tier manifests
  PHPT_BASELINE_TIER   tier to run when --tier is omitted
EOF
}

out_dir=${PHPT_BASELINE_DIR:-$repo_root/.runtime/phpt-baseline}
run_tier=${PHPT_BASELINE_TIER:-1000}
generate_only=0
classify_only=0

while [[ $# -gt 0 ]]; do
  case "$1" in
    --generate-only)
      generate_only=1
      shift
      ;;
    --classify-only)
      classify_only=1
      shift
      ;;
    --tier)
      [[ $# -ge 2 ]] || { echo "--tier requires a value" >&2; exit 2; }
      run_tier=$2
      shift 2
      ;;
    --out-dir)
      [[ $# -ge 2 ]] || { echo "--out-dir requires a value" >&2; exit 2; }
      out_dir=$2
      shift 2
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      if [[ "$1" == --* ]]; then
        echo "unknown option: $1" >&2
        usage >&2
        exit 2
      fi
      run_tier=$1
      shift
      ;;
  esac
done

if [[ "$generate_only" -eq 1 && "$classify_only" -eq 1 ]]; then
  echo "--generate-only and --classify-only are mutually exclusive" >&2
  exit 2
fi

if [[ "$run_tier" != "all" && ! "$run_tier" =~ ^[0-9]+$ ]]; then
  echo "--tier must be a positive integer or 'all': $run_tier" >&2
  exit 2
fi
if [[ "$run_tier" != "all" && "$run_tier" -le 0 ]]; then
  echo "--tier must be positive: $run_tier" >&2
  exit 2
fi

php_src="$(ptn_resolve_phpt_corpus "$repo_root")"
corpus_revision="$(ptn_phpt_corpus_revision "$php_src")"
stamp="$(date -u +%Y%m%dT%H%M%SZ)"
manifest_dir="$out_dir/$stamp"
inventory="$manifest_dir/inventory.txt"

mkdir -p "$manifest_dir"

bucket_names=(zend standard core)
bucket_roots=(Zend/tests ext/standard/tests tests)
bucket_files=()
bucket_counts=()

available_rows=0
for i in "${!bucket_names[@]}"; do
  root=${bucket_roots[$i]}
  if [[ ! -d "$php_src/$root" ]]; then
    echo "PHPT corpus bucket root missing: $php_src/$root" >&2
    exit 2
  fi

  rows_file="$manifest_dir/all-${bucket_names[$i]}.txt"
  (cd "$php_src" && find "$root" -type f -name '*.phpt' | LC_ALL=C sort) > "$rows_file"
  count=$(wc -l < "$rows_file")
  count=${count//[[:space:]]/}
  bucket_files[$i]=$rows_file
  bucket_counts[$i]=$count
  available_rows=$((available_rows + count))
done

if [[ "$available_rows" -eq 0 ]]; then
  echo "no PHPT rows found in broad baseline buckets" >&2
  exit 1
fi

default_tiers=(1000 5000 10000)
generation_tiers=("${default_tiers[@]}")
if [[ "$run_tier" != "all" ]]; then
  generation_tiers+=("$run_tier")
fi
mapfile -t generation_tiers < <(printf '%s\n' "${generation_tiers[@]}" | awk '!seen[$0]++' | sort -n)

declare -A manifest_by_tier=()

write_manifest() {
  local requested=$1
  local selected=$requested
  if [[ "$selected" -gt "$available_rows" ]]; then
    selected=$available_rows
  fi

  local manifest="$manifest_dir/phpt-baseline-${requested}.txt"
  local -a allocated=()
  local -a remainder=()
  local assigned=0

  for i in "${!bucket_names[@]}"; do
    allocated[$i]=$((selected * bucket_counts[$i] / available_rows))
    remainder[$i]=$((selected * bucket_counts[$i] % available_rows))
    assigned=$((assigned + allocated[$i]))
  done

  while [[ "$assigned" -lt "$selected" ]]; do
    local best=-1
    local best_remainder=-1
    for i in "${!bucket_names[@]}"; do
      if [[ "${allocated[$i]}" -lt "${bucket_counts[$i]}" && "${remainder[$i]}" -gt "$best_remainder" ]]; then
        best=$i
        best_remainder=${remainder[$i]}
      fi
    done
    if [[ "$best" -lt 0 ]]; then
      echo "could not allocate PHPT baseline rows for tier $requested" >&2
      exit 1
    fi
    allocated[$best]=$((allocated[$best] + 1))
    assigned=$((assigned + 1))
  done

  {
    echo "# Generated by tools/run-phpt-baseline.sh"
    echo "# generated-at: $stamp"
    echo "# corpus: $php_src"
    echo "# corpus-revision: $corpus_revision"
    echo "# requested-rows: $requested"
    echo "# selected-rows: $selected"
    echo "# source-buckets: Zend/tests, ext/standard/tests, tests"

    for i in "${!bucket_names[@]}"; do
      if [[ "${allocated[$i]}" -eq 0 ]]; then
        continue
      fi
      echo
      echo "# bucket: ${bucket_names[$i]} rows=${allocated[$i]}"
      head -n "${allocated[$i]}" "${bucket_files[$i]}"
    done
  } > "$manifest"

  manifest_by_tier[$requested]=$manifest
  printf 'manifest: tier=%s rows=%s zend=%s standard=%s core=%s path=%s\n' \
    "$requested" "$selected" "${allocated[0]}" "${allocated[1]}" "${allocated[2]}" "$manifest" \
    | tee -a "$inventory"
}

{
  echo "PHPT broad baseline $stamp"
  echo "corpus: $php_src"
  echo "corpus-revision: $corpus_revision"
  printf 'available: rows=%s zend=%s standard=%s core=%s\n' \
    "$available_rows" "${bucket_counts[0]}" "${bucket_counts[1]}" "${bucket_counts[2]}"
} | tee "$inventory"

for tier in "${generation_tiers[@]}"; do
  write_manifest "$tier"
done

if [[ "$generate_only" -eq 1 ]]; then
  echo "generated-only: $manifest_dir" | tee -a "$inventory"
  exit 0
fi

run_tiers=()
if [[ "$run_tier" == "all" ]]; then
  run_tiers=("${default_tiers[@]}")
else
  run_tiers=("$run_tier")
fi

for tier in "${run_tiers[@]}"; do
  manifest=${manifest_by_tier[$tier]:-}
  if [[ -z "$manifest" ]]; then
    echo "internal error: no generated manifest for tier $tier" >&2
    exit 1
  fi
  echo "running: tier=$tier manifest=$manifest"
  bounded_args=()
  if [[ "$classify_only" -eq 1 ]]; then
    bounded_args+=(--classify-only)
  fi
  "$repo_root/tools/run-bounded-phpt.sh" "${bounded_args[@]}" "$manifest"
done
