// Generated by tools/generate-json-metadata.pl from php-src ext/json.
// Source revision: 8c63ec400ce8e07c57a8d9499317b96a8beafb8b

pub(crate) const JSON_CONSTANT_NAMES: &[&str] = &[
    "JSON_HEX_TAG",
    "JSON_HEX_AMP",
    "JSON_HEX_APOS",
    "JSON_HEX_QUOT",
    "JSON_FORCE_OBJECT",
    "JSON_NUMERIC_CHECK",
    "JSON_UNESCAPED_SLASHES",
    "JSON_PRETTY_PRINT",
    "JSON_UNESCAPED_UNICODE",
    "JSON_PARTIAL_OUTPUT_ON_ERROR",
    "JSON_PRESERVE_ZERO_FRACTION",
    "JSON_UNESCAPED_LINE_TERMINATORS",
    "JSON_OBJECT_AS_ARRAY",
    "JSON_BIGINT_AS_STRING",
    "JSON_INVALID_UTF8_IGNORE",
    "JSON_INVALID_UTF8_SUBSTITUTE",
    "JSON_THROW_ON_ERROR",
    "JSON_ERROR_NONE",
    "JSON_ERROR_DEPTH",
    "JSON_ERROR_STATE_MISMATCH",
    "JSON_ERROR_CTRL_CHAR",
    "JSON_ERROR_SYNTAX",
    "JSON_ERROR_UTF8",
    "JSON_ERROR_RECURSION",
    "JSON_ERROR_INF_OR_NAN",
    "JSON_ERROR_UNSUPPORTED_TYPE",
    "JSON_ERROR_INVALID_PROPERTY_NAME",
    "JSON_ERROR_UTF16",
    "JSON_ERROR_NON_BACKED_ENUM",
];

pub(crate) fn is_json_constant_name(name: &str) -> bool {
    JSON_CONSTANT_NAMES
        .iter()
        .any(|candidate| *candidate == name)
}
