// @generated by tools/generate-php-src-metadata.sh from php-src@8c63ec400ce8e07c57a8d9499317b96a8beafb8b.
// Do not edit by hand.

pub const PHP_SRC_METADATA_REVISION: &str = "8c63ec400ce8e07c57a8d9499317b96a8beafb8b";
pub const SPRINTF_DEFAULT_FLOAT_PRECISION: i32 = 6;
pub const SPRINTF_MAX_FLOAT_PRECISION: i32 = 53;
pub const SPRINTF_NUM_BUFFER_SIZE: usize = 500;

pub const SCALAR_FORMAT_INI_DEFAULTS: &[(&str, &str)] =
    &[("precision", "14"), ("serialize_precision", "-1")];

pub const LOCALE_CONSTANT_NAMES: &[&str] = &[
    "LC_CTYPE",
    "LC_NUMERIC",
    "LC_TIME",
    "LC_COLLATE",
    "LC_MONETARY",
    "LC_ALL",
    "LC_MESSAGES",
];

pub const NL_LANGINFO_CONSTANT_NAMES: &[&str] = &[
    "ABDAY_1",
    "ABDAY_2",
    "ABDAY_3",
    "ABDAY_4",
    "ABDAY_5",
    "ABDAY_6",
    "ABDAY_7",
    "DAY_1",
    "DAY_2",
    "DAY_3",
    "DAY_4",
    "DAY_5",
    "DAY_6",
    "DAY_7",
    "ABMON_1",
    "ABMON_2",
    "ABMON_3",
    "ABMON_4",
    "ABMON_5",
    "ABMON_6",
    "ABMON_7",
    "ABMON_8",
    "ABMON_9",
    "ABMON_10",
    "ABMON_11",
    "ABMON_12",
    "MON_1",
    "MON_2",
    "MON_3",
    "MON_4",
    "MON_5",
    "MON_6",
    "MON_7",
    "MON_8",
    "MON_9",
    "MON_10",
    "MON_11",
    "MON_12",
    "AM_STR",
    "PM_STR",
    "D_T_FMT",
    "D_FMT",
    "T_FMT",
    "T_FMT_AMPM",
    "ERA",
    "ERA_YEAR",
    "ERA_D_T_FMT",
    "ERA_D_FMT",
    "ERA_T_FMT",
    "ALT_DIGITS",
    "INT_CURR_SYMBOL",
    "CURRENCY_SYMBOL",
    "CRNCYSTR",
    "MON_DECIMAL_POINT",
    "MON_THOUSANDS_SEP",
    "MON_GROUPING",
    "POSITIVE_SIGN",
    "NEGATIVE_SIGN",
    "INT_FRAC_DIGITS",
    "FRAC_DIGITS",
    "P_CS_PRECEDES",
    "P_SEP_BY_SPACE",
    "N_CS_PRECEDES",
    "N_SEP_BY_SPACE",
    "P_SIGN_POSN",
    "N_SIGN_POSN",
    "DECIMAL_POINT",
    "RADIXCHAR",
    "THOUSANDS_SEP",
    "THOUSEP",
    "GROUPING",
    "YESEXPR",
    "NOEXPR",
    "YESSTR",
    "NOSTR",
    "CODESET",
];

pub fn is_locale_or_nl_langinfo_constant_name(name: &str) -> bool {
    LOCALE_CONSTANT_NAMES
        .iter()
        .chain(NL_LANGINFO_CONSTANT_NAMES.iter())
        .any(|candidate| *candidate == name)
}

pub fn scalar_format_ini_canonical_name(name: &str) -> Option<&'static str> {
    SCALAR_FORMAT_INI_DEFAULTS
        .iter()
        .find_map(|(candidate, _)| candidate.eq_ignore_ascii_case(name).then_some(*candidate))
}

pub fn scalar_format_ini_default(name: &str) -> Option<&'static str> {
    SCALAR_FORMAT_INI_DEFAULTS
        .iter()
        .find_map(|(candidate, default)| candidate.eq_ignore_ascii_case(name).then_some(*default))
}
