use std::fs;
use std::path::Path;
use std::process::{Command, Output};

use php_compiler::{emit_asm_source, emit_ir_source, run_source};

const SOURCE: &str = r#"<?php
$int = 42;
$float = 2.5;
$string = "Ada\nLovelace";
$truthy = true;
$falsey = false;
$nothing = null;

echo $int, "\n";
print $float;
echo "\n", $string, "\n", $truthy, $falsey, $nothing, "!";
"#;

const EXPECTED_STDOUT: &str = "42\n2.5\nAda\nLovelace\n1!";

#[test]
fn phpc_run_handles_current_native_scalar_echo_assignment_subset() {
    let execution = run_source(SOURCE).unwrap();

    assert_eq!(execution.stdout, EXPECTED_STDOUT);
    assert_eq!(execution.exit_code, 0);
}

#[test]
fn emit_ir_lowers_literal_assignments_and_scalar_echoes() {
    let ir = emit_ir_source(SOURCE).unwrap();

    assert!(ir.contains("; generated by phpc milestone 1"), "{ir}");
    assert!(
        ir.contains("call i32 (ptr, ...) @printf(ptr @.fmt_int, i64 42)"),
        "{ir}"
    );
    assert!(
        ir.contains("call i32 (ptr, ...) @printf(ptr @.fmt_float, double 2.5)"),
        "{ir}"
    );
    assert!(ir.contains("Ada\\0ALovelace\\00"), "{ir}");
    assert!(ir.contains("ret i32 0"), "{ir}");
}

#[test]
fn emit_ir_keeps_false_and_null_echoes_silent() {
    let ir = emit_ir_source("<?php\necho false, null, \"done\";\n").unwrap();

    let printf_count = ir.matches("@printf").count();
    assert_eq!(printf_count, 2, "{ir}");
    assert!(ir.contains("c\"done\\00\""), "{ir}");
}

#[test]
fn emit_asm_lowers_scalar_echoes_through_available_backend() {
    let has_backend = ["clang", "llc", "cc"]
        .iter()
        .any(|command| Command::new(command).arg("--version").output().is_ok());
    if !has_backend {
        return;
    }

    let asm = emit_asm_source(SOURCE).unwrap();

    assert!(asm.contains("main"), "{asm}");
}

#[test]
fn native_scalar_echo_emit_ir_cli_snapshot_matches_committed_output() {
    let manifest_dir = Path::new(env!("CARGO_MANIFEST_DIR"));
    let workspace_root = manifest_dir
        .parent()
        .expect("compiler has a workspace root");
    let fixture =
        workspace_root.join("tests/fixtures/milestone180/native_scalar_echo_assignment.php");
    let relative_fixture = fixture
        .strip_prefix(workspace_root)
        .expect("fixture lives under workspace root")
        .to_str()
        .expect("fixture path is valid UTF-8")
        .to_string();

    let output = Command::new(env!("CARGO_BIN_EXE_phpc"))
        .current_dir(workspace_root)
        .args(["compile", &relative_fixture, "--emit-ir"])
        .output()
        .unwrap_or_else(|error| panic!("failed to compile {relative_fixture}: {error}"));

    let expected = fs::read_to_string(
        workspace_root
            .join("tests/fixtures/milestone180/native_scalar_echo_assignment_emit_ir.cli"),
    )
    .expect("native scalar echo CLI snapshot is readable");
    let actual = render_cli_snapshot(&output);

    assert_eq!(actual, expected);
}

fn render_cli_snapshot(output: &Output) -> String {
    let exit_code = output.status.code().unwrap_or(1);
    let stdout = String::from_utf8_lossy(&output.stdout);
    let stderr = String::from_utf8_lossy(&output.stderr);

    format!(
        "exit: {exit_code}\nstdout:\n{stdout}--- stdout end ---\nstderr:\n{stderr}--- stderr end ---\n"
    )
}
